# Genes específicos de panel

Vamos a considerar que los genes específicos de panel son aquellos que están en el top en muy pocos paneles y en el "bottom" la mayoría de las veces. 
Elegimos los threshold: 
- TOP: por encima del top 0.01
- BOTTOM: por debajo de 0.5

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/glow_matrix_clustered_no_NA.tsv',sep = '\t') 
df.head()
#df_np = df.set_index('SYMBOL').fillna(df.set_index('SYMBOL').max()).to_numpy()
gene_disease_matrix = df.set_index('SYMBOL')


panel_class = pd.read_csv('/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/filter_panels/final_reclasified_panels.tsv',sep = '\t', header=None)

In [3]:
panels_to_remove=pd.read_csv('/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/filter_panels/panels_including_others.txt',sep = '\t', header=None) 
list(panels_to_remove[0])

['Dilated_and_arrhythmogenic_cardiomyopathy',
 'Ectodermal_dysplasia',
 'Thoracic_aortic_aneurysm_or_dissection_(GMS)',
 'Childhood_solid_tumours_cancer_susceptibility',
 'Adult_solid_tumours_for_rare_disease',
 'Sarcoma_susceptibility',
 'Childhood_solid_tumours',
 'Undiagnosed_metabolic_disorders',
 'Lysosomal_storage_disorder',
 'Albinism_or_congenital_nystagmus',
 'Mitochondrial_disorders',
 'Ichthyosis_and_erythrokeratoderma',
 'Unexplained_young_onset_end-stage_renal_disease',
 'Lipodystrophy_-_childhood_onset',
 'Skeletal_dysplasia',
 'Structural_eye_disease',
 'Adult_solid_tumours_cancer_susceptibility',
 'Sarcoma_cancer_susceptibility',
 'Adult_onset_neurodegenerative_disorder',
 'Epidermolysis_bullosa_and_congenital_skin_fragility',
 'Paediatric_or_syndromic_cardiomyopathy',
 'Haematological_malignancies_cancer_susceptibility',
 'Haematological_malignancies_for_rare_disease',
 'Likely_inborn_error_of_metabolism_-_targeted_testing_not_possible',
 'Ophthalmological_ciliopathies',
 'GI_tract_tumours']

Eliminamos los paneles que contienen al 100% a otros.

In [4]:
panel_class = panel_class[~panel_class[1].isin(list(panels_to_remove[0]))]

Añadimos "_GA"

In [5]:
panel_list = [str(x + "_GA") for x in panel_class[1]]
panel_class[1] = panel_list

In [6]:
panel_class

,0,1
2,Cancer Programme+Tumour syndromes,Colorectal_cancer_pertinent_cancer_susceptibil...
4,Cancer Programme+Tumour syndromes,Head_and_neck_cancer_pertinent_cancer_suscepti...
5,Cancer Programme+Tumour syndromes,Neuroendocrine_cancer_pertinent_cancer_suscept...
6,Cancer Programme+Tumour syndromes,Renal_cancer_pertinent_cancer_susceptibility_GA
9,Cardiovascular disorders,Arrhythmogenic_right_ventricular_cardiomyopath...
...,...,...
204,Cancer Programme+Tumour syndromes,Inherited_phaeochromocytoma_and_paraganglioma_...
205,Cancer Programme+Tumour syndromes,Inherited_predisposition_to_acute_myeloid_leuk...
206,Cancer Programme+Tumour syndromes,Inherited_renal_cancer_GA
207,Cancer Programme+Tumour syndromes,Multiple_endocrine_tumours_GA
208,Cancer Programme+Tumour syndromes,Neurofibromatosis_Type_1_GA

In [7]:
from collections import Counter

d = Counter(panel_class[0])
d

Counter({'Neurology and neurodevelopmental disorders': 43,
         'Cancer Programme+Tumour syndromes': 16,
         'Endocrine disorders': 15,
         'Metabolic disorders': 14,
         'Cardiovascular disorders': 11,
         'Dermatological disorders': 11,
         'Dysmorphic and congenital abnormality syndromes': 10,
         'Gastroenterological disorders': 10,
         'Ophthalmological disorders': 10,
         'Renal and urinary tract disorders': 10,
         'Haematological and immunological disorders': 9,
         'Skeletal disorders': 8,
         'Ciliopathies': 7,
         'Respiratory disorders': 3,
         'Growth disorders': 2,
         'Hearing and ear disorders': 2,
         'Rheumatological disorders': 2})

Extraemos de la matriz solo los paneles que queremos analizar.

In [8]:
gene_disease_matrix=gene_disease_matrix.loc[:,panel_list] # quitamos los paneles que están incluidos en otros.

In [9]:
gene_disease_matrix # 183 columnas

,Colorectal_cancer_pertinent_cancer_susceptibility_GA,Head_and_neck_cancer_pertinent_cancer_susceptibility_GA,Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA,Renal_cancer_pertinent_cancer_susceptibility_GA,Arrhythmogenic_right_ventricular_cardiomyopathy_GA,ClinGen_Familial_thoracic_aortic_aneurysm_and_aortic_dissection_GA,Dilated_Cardiomyopathy_and_conduction_defects_GA,Familial_cerebral_small_vessel_disease_GA,Familial_non_syndromic_congenital_heart_disease_GA,Hypertrophic_cardiomyopathy_GA,...,Familial_rhabdomyosarcoma_GA,Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA,Inherited_ovarian_cancer_(without_breast_cancer)_GA,Inherited_pancreatic_cancer_GA,Inherited_phaeochromocytoma_and_paraganglioma_GA,Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA,Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA,Inherited_renal_cancer_GA,Multiple_endocrine_tumours_GA,Neurofibromatosis_Type_1_GA
SYMBOL,,,,,,,,,,,,,,,,,,,,,
FAAP20,5773.0,4.0,13424.0,5967.0,15627.0,17947.0,16494.0,16854.0,15375.0,17637.0,...,5818.0,8198.0,564.0,493.0,13937.0,14695.0,9970.0,11996.0,12204.0,4.0
FANCM,64.0,0.0,6109.0,579.0,3181.0,3460.0,3242.0,7658.0,1238.0,11642.0,...,143.0,189.0,20.0,65.0,6115.0,7112.0,316.0,6501.0,3855.0,1.0
POT1,413.0,394.0,6885.0,2316.0,1846.0,15023.0,6605.0,13689.0,12507.0,14375.0,...,943.0,4015.0,260.0,59.0,10747.0,11748.0,13.0,120.0,4663.0,475.0
FAAP100,1559.0,1.0,10504.0,1392.0,13018.0,16063.0,17750.0,15239.0,9291.0,17731.0,...,2797.0,2451.0,180.0,176.0,11121.0,13732.0,966.0,10167.0,10262.0,2.0
XRCC3,107.0,32.0,2606.0,566.0,5914.0,5296.0,10028.0,4564.0,6325.0,7421.0,...,219.0,255.0,1.0,73.0,1922.0,3057.0,400.0,2021.0,3741.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MTSS1L,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
C2orf71,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
FAM57B,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
FAM92A,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
WISP3,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0

Ponemos los **thresholds**

In [10]:
threshold_top=0.01 # por encima de
threshold_bottom=0.5 # por debajo de

In [11]:
max_valuedisease=gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].max(axis=0) # el valor máximo de cada uno de los paneles.

In [12]:
max_valuedisease

Colorectal_cancer_pertinent_cancer_susceptibility_GA              19557.0
Head_and_neck_cancer_pertinent_cancer_susceptibility_GA           22726.0
Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA          19661.0
Renal_cancer_pertinent_cancer_susceptibility_GA                   19570.0
Arrhythmogenic_right_ventricular_cardiomyopathy_GA                22270.0
                                                                   ...
Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA    19655.0
Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA      19688.0
Inherited_renal_cancer_GA                                         19573.0
Multiple_endocrine_tumours_GA                                     19737.0
Neurofibromatosis_Type_1_GA                                       22228.0
Length: 183, dtype: float64

En base al valor máximo de cada panel, obtenemos cual va a ser la posición de corte del top y del bottom.

## Top

In [13]:
division = [x*threshold_top for x in list(max_valuedisease)] 

max_valuedisease = pd.DataFrame(max_valuedisease)
max_valuedisease["top_ranking"] = division
max_valuedisease.T.iloc[1:]

comparison_df = pd.DataFrame([division] * gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].shape[0], columns=max_valuedisease.index)
comparison_df.index = gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].index
comparison_df # creamos este dataframe con el valor máximo del %top. Ahora compararemos nuestra tabla con esta (¿la posición 0,0 de glowmatrix es menor que la posición 0.0 de comparation_df?). Así calculamos el % de top. 
# estamos quitando los ceros. 
mask = (gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"] < comparison_df) & (gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"] != 0)

n_tops = mask.sum(axis = 1)
n_tops

SYMBOL
FAAP20     11
FANCM      23
POT1       15
FAAP100    14
XRCC3      17
           ..
MTSS1L      0
C2orf71     0
FAM57B      0
FAM92A      0
WISP3       0
Length: 24757, dtype: int64

In [14]:
d = (mask.loc["SDHA"])

pd.set_option('display.max_rows', d.shape[0]+1)
print(d)

Colorectal_cancer_pertinent_cancer_susceptibility_GA                                  False
Head_and_neck_cancer_pertinent_cancer_susceptibility_GA                               False
Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA                              False
Renal_cancer_pertinent_cancer_susceptibility_GA                                        True
Arrhythmogenic_right_ventricular_cardiomyopathy_GA                                    False
ClinGen_Familial_thoracic_aortic_aneurysm_and_aortic_dissection_GA                    False
Dilated_Cardiomyopathy_and_conduction_defects_GA                                       True
Familial_cerebral_small_vessel_disease_GA                                             False
Familial_non_syndromic_congenital_heart_disease_GA                                    False
Hypertrophic_cardiomyopathy_GA                                                        False
Long_QT_syndrome_GA                                                                   False
Primary_lymphoedema_GA                                                                False
Progressive_cardiac_conduction_disease_GA                                             False
Pulmonary_arterial_hypertension_GA                                                    False
Vascular_skin_disorders_GA                                                            False
Bardet_Biedl_syndrome_GA                                                              False
Neurological_ciliopathies_GA                                                          False
Primary_ciliary_disorders_GA                                                          False
Rare_multisystem_ciliopathy_disorders_GA                                              False
Renal_ciliopathies_GA                                                                 False
Respiratory_ciliopathies_including_non-CF_bronchiectasis_GA                           False
Skeletal_ciliopathies_GA                                                              False
Autosomal_recessive_congenital_ichthyosis_GA                                          False
Cutaneous_photosensitivity_with_a_likely_genetic_cause_GA                              True
Ectodermal_dysplasia_without_a_known_gene_mutation_GA                                 False
Epidermolysis_bullosa_GA                                                              False
Non-syndromic_hypotrichosis_GA                                                        False
Palmoplantar_keratoderma_and_erythrokeratodermas_GA                                   False
Mosaic_skin_disorders_-_deep_sequencing_GA                                            False
Palmoplantar_keratodermas_GA                                                          False
Pigmentary_skin_disorders_GA                                                          False
Primary_immunodeficiency_or_monogenic_inflammatory_bowel_disease_GA                   False
Clefting_GA                                                                           False
Fetal_anomalies_GA                                                                    False
Fetal_hydrops_GA                                                                      False
Laterality_disorders_and_isomerism_GA                                                 False
Radial_dysplasia_GA                                                                   False
RASopathies_GA                                                                        False
Severe_microcephaly_GA                                                                False
VACTERL-like_phenotypes_GA                                                            False
Vici_Syndrome_and_other_autophagy_disorders_GA                                        False
Xeroderma_pigmentosum,_Trichothiodystrophy_or_Cockayne_syndrome_GA                    False
Congenital_adrenal_hypoplasia_GA                                                      False
Congenital_hyperinsulinism_GA                                                         False
Congenital_hypothyroidism_GA                                                          False
Diabetes_with_additional_phenotypes_suggestive_of_a_monogenic_aetiology_GA            False
Disorders_of_sex_development_GA                                                       False
Familial_diabetes_GA                                                                  False
Familial_hyperparathyroidism_or_hypocalciuric_hypercalcaemia_GA                       False
Hypogonadotropic_hypogonadism_(GMS)_GA                                                False
Insulin_resistance_(including_lipodystrophy)_GA                                       False
IUGR_and_IGF_abnormalities_GA                                                         False
Monogenic_diabetes_GA                                                                 False
Neonatal_diabetes_GA                                                                  False
Pituitary_hormone_deficiency_GA                                                       False
Primary_ovarian_insufficiency_GA                                                      False
Severe_early-onset_obesity_GA                                                         False
Cholestasis_GA                                                                        False
Ductal_plate_malformation_GA                                                          False
Familial_Hirschsprung_Disease_GA                                                      False
Gastrointestinal_epithelial_barrier_disorders_GA                                      False
Gastrointestinal_neuromuscular_disorders_GA                                            True
Infantile_enterocolitis_&_monogenic_inflammatory_bowel_disease_GA                     False
Intestinal_failure_or_congenital_diarrhoea_GA                                         False
Neonatal_cholestasis_GA                                                                True
Non-syndromic_familial_congenital_anorectal_malformations_GA                          False
Paediatric_pseudo-obstruction_syndrome_GA                                             False
Beckwith-Wiedemann_syndrome_(BWS)_and_other_congenital_overgrowth_disorders_GA        False
Growth_failure_in_early_childhood_GA                                                  False
Inherited_bleeding_disorders_GA                                                       False
Autoinflammatory_disorders_GA                                                         False
Bleeding_and_platelet_disorders_GA                                                    False
Confirmed_Fanconi_anaemia_or_Bloom_syndrome_GA                                        False
Cytopenia_-_NOT_Fanconi_anaemia_GA                                                    False
Cytopenias_and_congenital_anaemias_GA                                                 False
Hereditary_Erythrocytosis_GA                                                          False
Rare_anaemia_GA                                                                       False
Thrombophilia_with_a_likely_monogenic_cause_GA                                        False
Corneal_dystrophy_GA                                                                  False
Deafness_and_congenital_structural_abnormalities_GA                                   False
Monogenic_hearing_loss_GA                                                             False
Congenital_disorders_of_glycosylation_GA                                              False
Hyperammonaemia_GA                                                                     True
Hypophosphataemia_or_rickets_GA                                                       False
Iron_metabolism_disorders_-_NOT_common_HFE_mutations_GA                               False
Ketotic_hypoglycaemia_GA                                                               True
Mitochondrial_disorder_with_complex_I_deficiency_GA                                    True
Mitochondrial_disorder_with_complex_III_deficiency_GA                                  True
Mitochondrial_disorder_with_complex_IV_deficiency_GA                                   True
Mitochondrial_disorder_with_complex_V_deficiency_GA                                    True
Mitochondrial_DNA_maintenance_disorder_GA                                              True
Mucopolysaccharideosis,_Gaucher,_Fabry_GA                                             False
Peroxisomal_disorders_GA                                                              False
Pyruvate_dehydrogenase_(PDH)_deficiency_GA                                             True
Glycogen_storage_disease_GA                                                           False
Acute_rhabdomyolysis_GA                                                                True
Adult_onset_dystonia,_chorea_or_related_movement_disorder_GA                          False
Adult_onset_hereditary_spastic_paraplegia_GA                                           True
Adult_onset_leukodystrophy_GA                                                         False
Arthrogryposis_GA                                                                     False
Ataxia_and_cerebellar_anomalies_-_narrow_panel_GA                                      True
Autism_GA                                                                             False
Brain_channelopathy_GA                                                                False
Cerebellar_hypoplasia_GA                                                              False
Cerebral_vascular_malformations_GA                                                    False
Childhood_onset_dystonia,_chorea_or_related_movement_disorder_GA                       True
Childhood_onset_hereditary_spastic_paraplegia_GA                                       True
Congenital_muscular_dystrophy_GA                                                      False
Congenital_myaesthenic_syndrome_GA                                                    False
Congenital_myopathy_GA                                                                False
Distal_myopathies_GA                                                                  False
Early_onset_dementia_(encompassing_fronto-temporal_dementia_and_prion_disease)_GA     False
Early_onset_dystonia_GA                                                                True
Early_onset_or_syndromic_epilepsy_GA                                                  False
Familial_dysautonomia_GA                                                              False
Hereditary_ataxia_GA                                                                   True
Hereditary_ataxia_with_onset_in_adulthood_GA                                           True
Hereditary_neuropathy_GA                                                               True
Hereditary_neuropathy_or_pain_disorder_GA                                              True
Hereditary_spastic_paraplegia_GA                                                       True
Holoprosencephaly_-_NOT_chromosomal_GA                                                False
Hydrocephalus_GA                                                                      False
Inherited_white_matter_disorders_GA                                                   False
Intellectual_disability_-_microarray_and_sequencing_GA                                False
Intracerebral_calcification_disorders_GA                                              False
Limb_girdle_muscular_dystrophies,_myofibrillar_myopathies_and_distal_myopathies_GA    False
Malformations_of_cortical_development_GA                                              False
Neuronal_ceroid_lipofuscinosis_GA                                                     False
Neurotransmitter_disorders_GA                                                         False
Paediatric_motor_neuronopathies_GA                                                    False
Pain_syndromes_GA                                                                     False
Parkinson_Disease_and_Complex_Parkinsonism_GA                                         False
Paroxysmal_central_nervous_system_disorders_GA                                        False
Rhabdomyolysis_and_metabolic_muscle_disorders_GA                                       True
Skeletal_Muscle_Channelopathies_GA                                                    False
Structural_basal_ganglia_disorders_GA                                                 False
White_matter_disorders_and_cerebral_calcification_-_narrow_panel_GA                   False
Hereditary_systemic_amyloidosis_GA                                                    False
Rare_genetic_inflammatory_skin_disorders_GA                                           False
Anophthalmia_or_microphthalmia_GA                                                     False
Bilateral_congenital_or_childhood_onset_cataracts_GA                                  False
Corneal_abnormalities_GA                                                              False
Glaucoma_(developmental)_GA                                                           False
Infantile_nystagmus_GA                                                                False
Ocular_and_oculo-cutaneous_albinism_GA                                                False
Ocular_coloboma_GA                                                                    False
Optic_neuropathy_GA                                                                    True
Retinal_disorders_GA                                                                  False
Atypical_haemolytic_uraemic_syndrome_GA                                               False
CAKUT_GA                                                                              False
Cystic_kidney_disease_GA                                                              False
Extreme_early-onset_hypertension_GA                                                   False
Nephrocalcinosis_or_nephrolithiasis_GA                                                False
Polycystic_liver_disease_GA                                                           False
Proteinuric_renal_disease_GA                                                          False
Renal_tubulopathies_GA                                                                False
Tubulointerstitial_kidney_disease_GA                                                  False
Unexplained_kidney_failure_in_young_people_GA                                         False
Familial_pulmonary_fibrosis_GA                                                        False
Pneumothorax_-_familial_GA                                                            False
Pulmonary_fibrosis_familial_GA                                                        False
Ehlers_Danlos_syndrome_with_a_likely_monogenic_cause_GA                               False
Periodic_fever_syndromes_GA                                                           False
Amelogenesis_imperfecta_GA                                                            False
Choanal_atresia_GA                                                                    False
Limb_disorders_GA                                                                     False
Osteogenesis_imperfecta_GA                                                            False
Osteopetrosis_GA                                                                      False
Rare_syndromic_craniosynostosis_or_isolated_multisuture_synostosis_GA                 False
Stickler_syndrome_GA                                                                  False
Thoracic_dystrophies_GA                                                               False
Endocrine_neoplasia_GA                                                                False
Familial_breast_cancer_GA                                                             False
Familial_rhabdomyosarcoma_GA                                                          False
Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA              False
Inherited_ovarian_cancer_(without_breast_cancer)_GA                                   False
Inherited_pancreatic_cancer_GA                                                        False
Inherited_phaeochromocytoma_and_paraganglioma_GA                                      False
Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA                        False
Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA                          False
Inherited_renal_cancer_GA                                                              True
Multiple_endocrine_tumours_GA                                                          True
Neurofibromatosis_Type_1_GA                                                           False
Name: SDHA, dtype: bool

## Bottom

In [15]:
division_bottom=[x*threshold_bottom for x in list(max_valuedisease[0])] 

max_valuedisease = pd.DataFrame(max_valuedisease)
max_valuedisease["bottom_ranking"] = division_bottom
max_valuedisease.T.iloc[1:]


comparison_bottom_df = pd.DataFrame([division_bottom] * gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].shape[0], columns=max_valuedisease.index)
comparison_bottom_df.index = gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].index
comparison_bottom_df # creamos este dataframe con el valor máximo del %top. Ahora compararemos nuestra tabla con esta (¿la posición 0,0 de glowmatrix es menor que la posición 0.0 de comparation_df?). Así calculamos el % de top. 

mask_bottom = (gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"] > comparison_bottom_df) & (gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"] != 0)

n_bottom = mask_bottom.sum(axis = 1)
n_bottom

SYMBOL
FAAP20     139
FANCM        5
POT1        66
FAAP100    117
XRCC3       15
          ...
MTSS1L     182
C2orf71    182
FAM57B     182
FAM92A     182
WISP3      183
Length: 24757, dtype: int64

## Número de Top y Bottom de cada gen:

In [16]:
ranking_n = pd.DataFrame(
    {'n_top': n_tops,
     'n_bottom': n_bottom
    })

ranking_n

         n_top  n_bottom
SYMBOL
FAAP20      11       139
FANCM       23         5
POT1        15        66
FAAP100     14       117
XRCC3       17        15
...        ...       ...
MTSS1L       0       182
C2orf71      0       182
FAM57B       0       182
FAM92A       0       182
WISP3        0       183

[24757 rows x 2 columns]

In [17]:
ranking_n.to_csv("/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/n_top_bottom.csv", header=True)

Vamos a seleccionar los que solo tienen un top y están en el bottom en el 90% de sus paneles.

In [17]:
top_1=ranking_n.query('n_top == 1 and n_bottom > 164' )  ## 164 sería el número de paneles (183) por 0.9 (es decir, bottom en el 90% de los paneles)
top_1

            n_top  n_bottom
SYMBOL
PRAMEF10        1       175
OR2Y1           1       165
MIR210          1       177
C6ORF132        1       181
MIR661          1       179
...           ...       ...
DSG2-AS1        1       182
SNHG22          1       182
EGFR-AS1        1       182
SLC9A3-AS1      1       182
ZC3H18-AS1      1       182

[192 rows x 2 columns]

Obtenemos 192 genes.

In [26]:
gene_disease_matrix
#for r in gene_disease_matrix.loc[top_1.index].shape[0]:

,Colorectal_cancer_pertinent_cancer_susceptibility_GA,Head_and_neck_cancer_pertinent_cancer_susceptibility_GA,Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA,Renal_cancer_pertinent_cancer_susceptibility_GA,Arrhythmogenic_right_ventricular_cardiomyopathy_GA,ClinGen_Familial_thoracic_aortic_aneurysm_and_aortic_dissection_GA,Dilated_Cardiomyopathy_and_conduction_defects_GA,Familial_cerebral_small_vessel_disease_GA,Familial_non_syndromic_congenital_heart_disease_GA,Hypertrophic_cardiomyopathy_GA,...,Familial_rhabdomyosarcoma_GA,Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA,Inherited_ovarian_cancer_(without_breast_cancer)_GA,Inherited_pancreatic_cancer_GA,Inherited_phaeochromocytoma_and_paraganglioma_GA,Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA,Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA,Inherited_renal_cancer_GA,Multiple_endocrine_tumours_GA,Neurofibromatosis_Type_1_GA
SYMBOL,,,,,,,,,,,,,,,,,,,,,
FAAP20,5773.0,4.0,13424.0,5967.0,15627.0,17947.0,16494.0,16854.0,15375.0,17637.0,...,5818.0,8198.0,564.0,493.0,13937.0,14695.0,9970.0,11996.0,12204.0,4.0
FANCM,64.0,0.0,6109.0,579.0,3181.0,3460.0,3242.0,7658.0,1238.0,11642.0,...,143.0,189.0,20.0,65.0,6115.0,7112.0,316.0,6501.0,3855.0,1.0
POT1,413.0,394.0,6885.0,2316.0,1846.0,15023.0,6605.0,13689.0,12507.0,14375.0,...,943.0,4015.0,260.0,59.0,10747.0,11748.0,13.0,120.0,4663.0,475.0
FAAP100,1559.0,1.0,10504.0,1392.0,13018.0,16063.0,17750.0,15239.0,9291.0,17731.0,...,2797.0,2451.0,180.0,176.0,11121.0,13732.0,966.0,10167.0,10262.0,2.0
XRCC3,107.0,32.0,2606.0,566.0,5914.0,5296.0,10028.0,4564.0,6325.0,7421.0,...,219.0,255.0,1.0,73.0,1922.0,3057.0,400.0,2021.0,3741.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MTSS1L,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
C2orf71,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
FAM57B,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
FAM92A,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0
WISP3,19557.0,22726.0,19661.0,19570.0,22270.0,22353.0,20524.0,19592.0,19673.0,21736.0,...,19586.0,19701.0,22256.0,22256.0,19579.0,19655.0,19688.0,19573.0,19737.0,22228.0

In [50]:
disease_specific_g = {}

for r in top_1.index:
    #print(mask.loc[r,mask.loc[r] == True].index[0]) 
    disease_specific_g[r] = mask.loc[r,mask.loc[r] == True].index[0]

In [74]:
#mask.loc["GAGE12C"]
max_valuedisease.loc["Ocular_and_oculo-cutaneous_albinism_GA"]

0                 22405.00
top_ranking         224.05
bottom_ranking    11202.50
Name: Ocular_and_oculo-cutaneous_albinism_GA, dtype: float64

In [63]:
df_disease_specific_g = pd.DataFrame.from_dict(disease_specific_g, orient = "index", columns=["Panel"])

In [64]:
df_disease_specific_g

                                                        Panel
PRAMEF10                        Multiple_endocrine_tumours_GA
OR2Y1       Xeroderma_pigmentosum,_Trichothiodystrophy_or_...
MIR210              Progressive_cardiac_conduction_disease_GA
C6ORF132                      Hypophosphataemia_or_rickets_GA
MIR661              Progressive_cardiac_conduction_disease_GA
...                                                       ...
DSG2-AS1    Arrhythmogenic_right_ventricular_cardiomyopath...
SNHG22          Intestinal_failure_or_congenital_diarrhoea_GA
EGFR-AS1        Intestinal_failure_or_congenital_diarrhoea_GA
SLC9A3-AS1      Intestinal_failure_or_congenital_diarrhoea_GA
ZC3H18-AS1            Atypical_haemolytic_uraemic_syndrome_GA

[192 rows x 1 columns]

In [67]:
top_1.to_csv("/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/genes_panel_specific.txt")
df_disease_specific_g.to_csv("/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/genes_panel_specific_panels.csv", header=False)

In [21]:
import pandas as pd
genes_top1 = pd.read_csv('/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/genes_panel_specific.txt',sep = ',') 
genes_top1
genes_panelApp = pd.read_csv('/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/PANELAPP_ALL_GENES_sep.txt',sep = '\t', header=None) 
#genes_panelApp

Genes que están en PanelAPP

In [22]:
[x for x in genes_top1["SYMBOL"] if x in list(genes_panelApp[0]) ]

['MIR675', 'SNURF', 'PROSER1', 'PROSER2', 'FAM47A']

# Genes específicos de categoría

Vamos a considerar que para que un gen sea específico de categoría, tiene que estar top en más del 50% de los paneles de su categoría y bottom en el resto. 

- De cada gen, obtenemos en qué paneles está en posición top (más arriba del 0.01) y en qué paneles está bottom (por debajo del 0.5). Habrá valores que quedarán en medio.
- Una vez tenemos esta información, vamos gen por gen, cogiendo los paneles pertenecientes a cada categoría. Si más de la mitad de los paneles son TOPs, consideramos que ese grupo es TOP para ese gen. Si más de la mitad de los paneles están BOTTOM, consideramos que ese panel es BOTTOM para ese gen. Si ni una cosa de la otra, es "MIDDLE".
- Seleccionamos los genes que tienen una única categoría TOP y tienen más de 10 BOTTOM (que sería más de la mitad de los paneles).

In [75]:
panel_class

,0,1
2,Cancer Programme+Tumour syndromes,Colorectal_cancer_pertinent_cancer_susceptibil...
4,Cancer Programme+Tumour syndromes,Head_and_neck_cancer_pertinent_cancer_suscepti...
5,Cancer Programme+Tumour syndromes,Neuroendocrine_cancer_pertinent_cancer_suscept...
6,Cancer Programme+Tumour syndromes,Renal_cancer_pertinent_cancer_susceptibility_GA
9,Cardiovascular disorders,Arrhythmogenic_right_ventricular_cardiomyopath...
10,Cardiovascular disorders,ClinGen_Familial_thoracic_aortic_aneurysm_and_...
12,Cardiovascular disorders,Dilated_Cardiomyopathy_and_conduction_defects_GA
13,Cardiovascular disorders,Familial_cerebral_small_vessel_disease_GA
14,Cardiovascular disorders,Familial_non_syndromic_congenital_heart_diseas...
15,Cardiovascular disorders,Hypertrophic_cardiomyopathy_GA
16,Cardiovascular disorders,Long_QT_syndrome_GA
18,Cardiovascular disorders,Primary_lymphoedema_GA
19,Cardiovascular disorders,Progressive_cardiac_conduction_disease_GA
20,Cardiovascular disorders,Pulmonary_arterial_hypertension_GA
22,Cardiovascular disorders,Vascular_skin_disorders_GA
23,Ciliopathies,Bardet_Biedl_syndrome_GA
24,Ciliopathies,Neurological_ciliopathies_GA
26,Ciliopathies,Primary_ciliary_disorders_GA
27,Ciliopathies,Rare_multisystem_ciliopathy_disorders_GA
28,Ciliopathies,Renal_ciliopathies_GA
29,Ciliopathies,Respiratory_ciliopathies_including_non-CF_bron...
30,Ciliopathies,Skeletal_ciliopathies_GA
31,Dermatological disorders,Autosomal_recessive_congenital_ichthyosis_GA
32,Dermatological disorders,Cutaneous_photosensitivity_with_a_likely_genet...
34,Dermatological disorders,Ectodermal_dysplasia_without_a_known_gene_muta...
35,Dermatological disorders,Epidermolysis_bullosa_GA
38,Dermatological disorders,Non-syndromic_hypotrichosis_GA
39,Dermatological disorders,Palmoplantar_keratoderma_and_erythrokeratoderm...
40,Dermatological disorders,Mosaic_skin_disorders_-_deep_sequencing_GA
41,Dermatological disorders,Palmoplantar_keratodermas_GA
42,Dermatological disorders,Pigmentary_skin_disorders_GA
43,Dermatological disorders,Primary_immunodeficiency_or_monogenic_inflamma...
44,Dysmorphic and congenital abnormality syndromes,Clefting_GA
45,Dysmorphic and congenital abnormality syndromes,Fetal_anomalies_GA
46,Dysmorphic and congenital abnormality syndromes,Fetal_hydrops_GA
47,Dysmorphic and congenital abnormality syndromes,Laterality_disorders_and_isomerism_GA
48,Dysmorphic and congenital abnormality syndromes,Radial_dysplasia_GA
49,Dysmorphic and congenital abnormality syndromes,RASopathies_GA
50,Dysmorphic and congenital abnormality syndromes,Severe_microcephaly_GA
51,Dysmorphic and congenital abnormality syndromes,VACTERL-like_phenotypes_GA
52,Dysmorphic and congenital abnormality syndromes,Vici_Syndrome_and_other_autophagy_disorders_GA
53,Dysmorphic and congenital abnormality syndromes,"Xeroderma_pigmentosum,_Trichothiodystrophy_or_..."
54,Endocrine disorders,Congenital_adrenal_hypoplasia_GA
55,Endocrine disorders,Congenital_hyperinsulinism_GA
56,Endocrine disorders,Congenital_hypothyroidism_GA
57,Endocrine disorders,Diabetes_with_additional_phenotypes_suggestive...
58,Endocrine disorders,Disorders_of_sex_development_GA
59,Endocrine disorders,Familial_diabetes_GA
60,Endocrine disorders,Familial_hyperparathyroidism_or_hypocalciuric_...
61,Endocrine disorders,Hypogonadotropic_hypogonadism_(GMS)_GA
62,Endocrine disorders,Insulin_resistance_(including_lipodystrophy)_GA
63,Endocrine disorders,IUGR_and_IGF_abnormalities_GA
65,Endocrine disorders,Monogenic_diabetes_GA
66,Endocrine disorders,Neonatal_diabetes_GA
67,Endocrine disorders,Pituitary_hormone_deficiency_GA
68,Endocrine disorders,Primary_ovarian_insufficiency_GA
69,Endocrine disorders,Severe_early-onset_obesity_GA
70,Gastroenterological disorders,Cholestasis_GA
71,Gastroenterological disorders,Ductal_plate_malformation_GA
72,Gastroenterological disorders,Familial_Hirschsprung_Disease_GA
73,Gastroenterological disorders,Gastrointestinal_epithelial_barrier_disorders_GA
74,Gastroenterological disorders,Gastrointestinal_neuromuscular_disorders_GA
75,Gastroenterological disorders,Infantile_enterocolitis_&_monogenic_inflammato...
76,Gastroenterological disorders,Intestinal_failure_or_congenital_diarrhoea_GA
77,Gastroenterological disorders,Neonatal_cholestasis_GA
78,Gastroenterological disorders,Non-syndromic_familial_congenital_anorectal_ma...
79,Gastroenterological disorders,Paediatric_pseudo-obstruction_syndrome_GA
80,Growth disorders,Beckwith-Wiedemann_syndrome_(BWS)_and_other_co...
81,Growth disorders,Growth_failure_in_early_childhood_GA
82,Haematological and immunological disorders,Inherited_bleeding_disorders_GA
83,Haematological and immunological disorders,Autoinflammatory_disorders_GA
84,Haematological and immunological disorders,Bleeding_and_platelet_disorders_GA
85,Haematological and immunological disorders,Confirmed_Fanconi_anaemia_or_Bloom_syndrome_GA
86,Haematological and immunological disorders,Cytopenia_-_NOT_Fanconi_anaemia_GA
87,Haematological and immunological disorders,Cytopenias_and_congenital_anaemias_GA
88,Haematological and immunological disorders,Hereditary_Erythrocytosis_GA
89,Haematological and immunological disorders,Rare_anaemia_GA
90,Haematological and immunological disorders,Thrombophilia_with_a_likely_monogenic_cause_GA
91,Ophthalmological disorders,Corneal_dystrophy_GA
92,Hearing and ear disorders,Deafness_and_congenital_structural_abnormaliti...
93,Hearing and ear disorders,Monogenic_hearing_loss_GA
94,Metabolic disorders,Congenital_disorders_of_glycosylation_GA
95,Metabolic disorders,Hyperammonaemia_GA
96,Metabolic disorders,Hypophosphataemia_or_rickets_GA
97,Metabolic disorders,Iron_metabolism_disorders_-_NOT_common_HFE_mut...
98,Metabolic disorders,Ketotic_hypoglycaemia_GA
102,Metabolic disorders,Mitochondrial_disorder_with_complex_I_deficien...
103,Metabolic disorders,Mitochondrial_disorder_with_complex_III_defici...
104,Metabolic disorders,Mitochondrial_disorder_with_complex_IV_deficie...
105,Metabolic disorders,Mitochondrial_disorder_with_complex_V_deficien...
106,Metabolic disorders,Mitochondrial_DNA_maintenance_disorder_GA
107,Metabolic disorders,"Mucopolysaccharideosis,_Gaucher,_Fabry_GA"
108,Metabolic disorders,Peroxisomal_disorders_GA
109,Metabolic disorders,Pyruvate_dehydrogenase_(PDH)_deficiency_GA
111,Metabolic disorders,Glycogen_storage_disease_GA
112,Neurology and neurodevelopmental disorders,Acute_rhabdomyolysis_GA
113,Neurology and neurodevelopmental disorders,"Adult_onset_dystonia,_chorea_or_related_moveme..."
114,Neurology and neurodevelopmental disorders,Adult_onset_hereditary_spastic_paraplegia_GA
115,Neurology and neurodevelopmental disorders,Adult_onset_leukodystrophy_GA
117,Neurology and neurodevelopmental disorders,Arthrogryposis_GA
118,Neurology and neurodevelopmental disorders,Ataxia_and_cerebellar_anomalies_-_narrow_panel_GA
119,Neurology and neurodevelopmental disorders,Autism_GA
120,Neurology and neurodevelopmental disorders,Brain_channelopathy_GA
121,Neurology and neurodevelopmental disorders,Cerebellar_hypoplasia_GA
122,Neurology and neurodevelopmental disorders,Cerebral_vascular_malformations_GA
123,Neurology and neurodevelopmental disorders,"Childhood_onset_dystonia,_chorea_or_related_mo..."
124,Neurology and neurodevelopmental disorders,Childhood_onset_hereditary_spastic_paraplegia_GA
125,Neurology and neurodevelopmental disorders,Congenital_muscular_dystrophy_GA
126,Neurology and neurodevelopmental disorders,Congenital_myaesthenic_syndrome_GA
127,Neurology and neurodevelopmental disorders,Congenital_myopathy_GA
128,Neurology and neurodevelopmental disorders,Distal_myopathies_GA
129,Neurology and neurodevelopmental disorders,Early_onset_dementia_(encompassing_fronto-temp...
130,Neurology and neurodevelopmental disorders,Early_onset_dystonia_GA
131,Neurology and neurodevelopmental disorders,Early_onset_or_syndromic_epilepsy_GA
132,Neurology and neurodevelopmental disorders,Familial_dysautonomia_GA
133,Neurology and neurodevelopmental disorders,Hereditary_ataxia_GA
134,Neurology and neurodevelopmental disorders,Hereditary_ataxia_with_onset_in_adulthood_GA
135,Neurology and neurodevelopmental disorders,Hereditary_neuropathy_GA
136,Neurology and neurodevelopmental disorders,Hereditary_neuropathy_or_pain_disorder_GA
137,Neurology and neurodevelopmental disorders,Hereditary_spastic_paraplegia_GA
138,Neurology and neurodevelopmental disorders,Holoprosencephaly_-_NOT_chromosomal_GA
139,Neurology and neurodevelopmental disorders,Hydrocephalus_GA
140,Neurology and neurodevelopmental disorders,Inherited_white_matter_disorders_GA
141,Neurology and neurodevelopmental disorders,Intellectual_disability_-_microarray_and_seque...
142,Neurology and neurodevelopmental disorders,Intracerebral_calcification_disorders_GA
143,Neurology and neurodevelopmental disorders,"Limb_girdle_muscular_dystrophies,_myofibrillar..."
144,Neurology and neurodevelopmental disorders,Malformations_of_cortical_development_GA
145,Neurology and neurodevelopmental disorders,Neuronal_ceroid_lipofuscinosis_GA
146,Neurology and neurodevelopmental disorders,Neurotransmitter_disorders_GA
147,Neurology and neurodevelopmental disorders,Paediatric_motor_neuronopathies_GA
148,Neurology and neurodevelopmental disorders,Pain_syndromes_GA
149,Neurology and neurodevelopmental disorders,Parkinson_Disease_and_Complex_Parkinsonism_GA
150,Neurology and neurodevelopmental disorders,Paroxysmal_central_nervous_system_disorders_GA
151,Neurology and neurodevelopmental disorders,Rhabdomyolysis_and_metabolic_muscle_disorders_GA
152,Neurology and neurodevelopmental disorders,Skeletal_Muscle_Channelopathies_GA
153,Neurology and neurodevelopmental disorders,Structural_basal_ganglia_disorders_GA
154,Neurology and neurodevelopmental disorders,White_matter_disorders_and_cerebral_calcificat...
155,Neurology and neurodevelopmental disorders,Hereditary_systemic_amyloidosis_GA
156,Dermatological disorders,Rare_genetic_inflammatory_skin_disorders_GA
159,Ophthalmological disorders,Anophthalmia_or_microphthalmia_GA
160,Ophthalmological disorders,Bilateral_congenital_or_childhood_onset_catara...
161,Ophthalmological disorders,Corneal_abnormalities_GA
162,Ophthalmological disorders,Glaucoma_(developmental)_GA
163,Ophthalmological disorders,Infantile_nystagmus_GA
164,Ophthalmological disorders,Ocular_and_oculo-cutaneous_albinism_GA
165,Ophthalmological disorders,Ocular_coloboma_GA
166,Ophthalmological disorders,Optic_neuropathy_GA
167,Ophthalmological disorders,Retinal_disorders_GA
168,Renal and urinary tract disorders,Atypical_haemolytic_uraemic_syndrome_GA
169,Renal and urinary tract disorders,CAKUT_GA
170,Renal and urinary tract disorders,Cystic_kidney_disease_GA
171,Renal and urinary tract disorders,Extreme_early-onset_hypertension_GA
172,Renal and urinary tract disorders,Nephrocalcinosis_or_nephrolithiasis_GA
173,Renal and urinary tract disorders,Polycystic_liver_disease_GA
174,Renal and urinary tract disorders,Proteinuric_renal_disease_GA
175,Renal and urinary tract disorders,Renal_tubulopathies_GA
176,Renal and urinary tract disorders,Tubulointerstitial_kidney_disease_GA
177,Renal and urinary tract disorders,Unexplained_kidney_failure_in_young_people_GA
179,Respiratory disorders,Familial_pulmonary_fibrosis_GA
180,Respiratory disorders,Pneumothorax_-_familial_GA
181,Respiratory disorders,Pulmonary_fibrosis_familial_GA
182,Rheumatological disorders,Ehlers_Danlos_syndrome_with_a_likely_monogenic...
183,Rheumatological disorders,Periodic_fever_syndromes_GA
184,Skeletal disorders,Amelogenesis_imperfecta_GA
185,Skeletal disorders,Choanal_atresia_GA
186,Skeletal disorders,Limb_disorders_GA
187,Skeletal disorders,Osteogenesis_imperfecta_GA
188,Skeletal disorders,Osteopetrosis_GA
189,Skeletal disorders,Rare_syndromic_craniosynostosis_or_isolated_mu...
191,Skeletal disorders,Stickler_syndrome_GA
192,Skeletal disorders,Thoracic_dystrophies_GA
195,Cancer Programme+Tumour syndromes,Endocrine_neoplasia_GA
196,Cancer Programme+Tumour syndromes,Familial_breast_cancer_GA
197,Cancer Programme+Tumour syndromes,Familial_rhabdomyosarcoma_GA
198,Cancer Programme+Tumour syndromes,Familial_Tumours_Syndromes_of_the_central_&_pe...
201,Cancer Programme+Tumour syndromes,Inherited_ovarian_cancer_(without_breast_cance...
202,Cancer Programme+Tumour syndromes,Inherited_pancreatic_cancer_GA
203,Cancer Programme+Tumour syndromes,Inherited_phaeochromocytoma_and_paraganglioma_GA
204,Cancer Programme+Tumour syndromes,Inherited_phaeochromocytoma_and_paraganglioma_...
205,Cancer Programme+Tumour syndromes,Inherited_predisposition_to_acute_myeloid_leuk...
206,Cancer Programme+Tumour syndromes,Inherited_renal_cancer_GA
207,Cancer Programme+Tumour syndromes,Multiple_endocrine_tumours_GA
208,Cancer Programme+Tumour syndromes,Neurofibromatosis_Type_1_GA

In [76]:
threshold_top=0.05 # por encima de
threshold_bottom=0.5 # por debajo de 
max_valuedisease=gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].max(axis=0) # el valor máximo de cada uno de los paneles.

In [77]:
class_top_bottom = pd.DataFrame(columns=list(set(panel_class[0])), 
            index = gene_disease_matrix.index)
class_top_bottom

,Cancer Programme+Tumour syndromes,Gastroenterological disorders,Cardiovascular disorders,Haematological and immunological disorders,Ciliopathies,Skeletal disorders,Dermatological disorders,Endocrine disorders,Hearing and ear disorders,Renal and urinary tract disorders,Rheumatological disorders,Growth disorders,Ophthalmological disorders,Respiratory disorders,Neurology and neurodevelopmental disorders,Dysmorphic and congenital abnormality syndromes,Metabolic disorders
SYMBOL,,,,,,,,,,,,,,,,,
FAAP20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FANCM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
POT1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAAP100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
XRCC3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MTSS1L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C2orf71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAM57B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAM92A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WISP3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
division = [x*threshold_top for x in list(max_valuedisease)] 

max_valuedisease = pd.DataFrame(max_valuedisease)
max_valuedisease["top_ranking"] = division
max_valuedisease.T.iloc[1:]

comparison_df = pd.DataFrame([division] * gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].shape[0], columns=max_valuedisease.index)
comparison_df.index = gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"].index
comparison_df # creamos este dataframe con el valor máximo del %top. Ahora compararemos nuestra tabla con esta (¿la posición 0,0 de glowmatrix es menor que la posición 0.0 de comparation_df?). Así calculamos el % de top. 

mask = (gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"] < comparison_df) & (gene_disease_matrix.loc[:, gene_disease_matrix.columns != "Cluster"] != 0)


top_bottom = mask
top_bottom

,Colorectal_cancer_pertinent_cancer_susceptibility_GA,Head_and_neck_cancer_pertinent_cancer_susceptibility_GA,Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA,Renal_cancer_pertinent_cancer_susceptibility_GA,Arrhythmogenic_right_ventricular_cardiomyopathy_GA,ClinGen_Familial_thoracic_aortic_aneurysm_and_aortic_dissection_GA,Dilated_Cardiomyopathy_and_conduction_defects_GA,Familial_cerebral_small_vessel_disease_GA,Familial_non_syndromic_congenital_heart_disease_GA,Hypertrophic_cardiomyopathy_GA,...,Familial_rhabdomyosarcoma_GA,Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA,Inherited_ovarian_cancer_(without_breast_cancer)_GA,Inherited_pancreatic_cancer_GA,Inherited_phaeochromocytoma_and_paraganglioma_GA,Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA,Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA,Inherited_renal_cancer_GA,Multiple_endocrine_tumours_GA,Neurofibromatosis_Type_1_GA
SYMBOL,,,,,,,,,,,,,,,,,,,,,
FAAP20,False,True,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,True
FANCM,True,False,False,True,False,False,False,False,False,False,...,True,True,True,True,False,False,True,False,False,True
POT1,True,True,False,False,False,False,False,False,False,False,...,True,False,True,True,False,False,True,True,False,True
FAAP100,False,True,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,True,False,False,True
XRCC3,True,True,False,True,False,False,False,False,False,False,...,True,True,True,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MTSS1L,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
C2orf71,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
FAM57B,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
FAM92A,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
WISP3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [79]:
max_valuedisease

                                                          0  top_ranking
Colorectal_cancer_pertinent_cancer_susceptibili...  19557.0       977.85
Head_and_neck_cancer_pertinent_cancer_susceptib...  22726.0      1136.30
Neuroendocrine_cancer_pertinent_cancer_suscepti...  19661.0       983.05
Renal_cancer_pertinent_cancer_susceptibility_GA     19570.0       978.50
Arrhythmogenic_right_ventricular_cardiomyopathy_GA  22270.0      1113.50
ClinGen_Familial_thoracic_aortic_aneurysm_and_a...  22353.0      1117.65
Dilated_Cardiomyopathy_and_conduction_defects_GA    20524.0      1026.20
Familial_cerebral_small_vessel_disease_GA           19592.0       979.60
Familial_non_syndromic_congenital_heart_disease_GA  19673.0       983.65
Hypertrophic_cardiomyopathy_GA                      21736.0      1086.80
Long_QT_syndrome_GA                                 22247.0      1112.35
Primary_lymphoedema_GA                              19492.0       974.60
Progressive_cardiac_conduction_disease_GA           22238.0      1111.90
Pulmonary_arterial_hypertension_GA                  19514.0       975.70
Vascular_skin_disorders_GA                          19544.0       977.20
Bardet_Biedl_syndrome_GA                            21007.0      1050.35
Neurological_ciliopathies_GA                        22196.0      1109.80
Primary_ciliary_disorders_GA                        22312.0      1115.60
Rare_multisystem_ciliopathy_disorders_GA            20938.0      1046.90
Renal_ciliopathies_GA                               21738.0      1086.90
Respiratory_ciliopathies_including_non-CF_bronc...  21142.0      1057.10
Skeletal_ciliopathies_GA                            22213.0      1110.65
Autosomal_recessive_congenital_ichthyosis_GA        19497.0       974.85
Cutaneous_photosensitivity_with_a_likely_geneti...  19511.0       975.55
Ectodermal_dysplasia_without_a_known_gene_mutat...  19688.0       984.40
Epidermolysis_bullosa_GA                            21793.0      1089.65
Non-syndromic_hypotrichosis_GA                      20531.0      1026.55
Palmoplantar_keratoderma_and_erythrokeratoderma...  21135.0      1056.75
Mosaic_skin_disorders_-_deep_sequencing_GA          19561.0       978.05
Palmoplantar_keratodermas_GA                        19546.0       977.30
Pigmentary_skin_disorders_GA                        19552.0       977.60
Primary_immunodeficiency_or_monogenic_inflammat...  22417.0      1120.85
Clefting_GA                                         19645.0       982.25
Fetal_anomalies_GA                                  19586.0       979.30
Fetal_hydrops_GA                                    20484.0      1024.20
Laterality_disorders_and_isomerism_GA               21136.0      1056.80
Radial_dysplasia_GA                                 22705.0      1135.25
RASopathies_GA                                      22805.0      1140.25
Severe_microcephaly_GA                              22019.0      1100.95
VACTERL-like_phenotypes_GA                          19464.0       973.20
Vici_Syndrome_and_other_autophagy_disorders_GA      19699.0       984.95
Xeroderma_pigmentosum,_Trichothiodystrophy_or_C...  22717.0      1135.85
Congenital_adrenal_hypoplasia_GA                    19734.0       986.70
Congenital_hyperinsulinism_GA                       19644.0       982.20
Congenital_hypothyroidism_GA                        19660.0       983.00
Diabetes_with_additional_phenotypes_suggestive_...  19479.0       973.95
Disorders_of_sex_development_GA                     19494.0       974.70
Familial_diabetes_GA                                22197.0      1109.85
Familial_hyperparathyroidism_or_hypocalciuric_h...  19576.0       978.80
Hypogonadotropic_hypogonadism_(GMS)_GA              19652.0       982.60
Insulin_resistance_(including_lipodystrophy)_GA     19526.0       976.30
IUGR_and_IGF_abnormalities_GA                       19435.0       971.75
Monogenic_diabetes_GA                               22305.0      1115.25
Neonatal_diabetes_GA                                22209.0      1110.45
Pituitary_hormone_deficiency_GA                     19736.0       986.80
Primary_ovarian_insufficiency_GA                    19411.0       970.55
Severe_early-onset_obesity_GA                       21018.0      1050.90
Cholestasis_GA                                      19494.0       974.70
Ductal_plate_malformation_GA                        19716.0       985.80
Familial_Hirschsprung_Disease_GA                    19724.0       986.20
Gastrointestinal_epithelial_barrier_disorders_GA    20426.0      1021.30
Gastrointestinal_neuromuscular_disorders_GA         20421.0      1021.05
Infantile_enterocolitis_&_monogenic_inflammator...  20419.0      1020.95
Intestinal_failure_or_congenital_diarrhoea_GA       22700.0      1135.00
Neonatal_cholestasis_GA                             19503.0       975.15
Non-syndromic_familial_congenital_anorectal_mal...  20555.0      1027.75
Paediatric_pseudo-obstruction_syndrome_GA           19589.0       979.45
Beckwith-Wiedemann_syndrome_(BWS)_and_other_con...  22224.0      1111.20
Growth_failure_in_early_childhood_GA                22257.0      1112.85
Inherited_bleeding_disorders_GA                     19452.0       972.60
Autoinflammatory_disorders_GA                       19753.0       987.65
Bleeding_and_platelet_disorders_GA                  20353.0      1017.65
Confirmed_Fanconi_anaemia_or_Bloom_syndrome_GA      22228.0      1111.40
Cytopenia_-_NOT_Fanconi_anaemia_GA                  20440.0      1022.00
Cytopenias_and_congenital_anaemias_GA               22224.0      1111.20
Hereditary_Erythrocytosis_GA                        19696.0       984.80
Rare_anaemia_GA                                     19768.0       988.40
Thrombophilia_with_a_likely_monogenic_cause_GA      19523.0       976.15
Corneal_dystrophy_GA                                19512.0       975.60
Deafness_and_congenital_structural_abnormalitie...  22304.0      1115.20
Monogenic_hearing_loss_GA                           19536.0       976.80
Congenital_disorders_of_glycosylation_GA            20890.0      1044.50
Hyperammonaemia_GA                                  19638.0       981.90
Hypophosphataemia_or_rickets_GA                     19740.0       987.00
Iron_metabolism_disorders_-_NOT_common_HFE_muta...  19708.0       985.40
Ketotic_hypoglycaemia_GA                            19578.0       978.90
Mitochondrial_disorder_with_complex_I_deficienc...  20415.0      1020.75
Mitochondrial_disorder_with_complex_III_deficie...  20981.0      1049.05
Mitochondrial_disorder_with_complex_IV_deficien...  21763.0      1088.15
Mitochondrial_disorder_with_complex_V_deficienc...  20973.0      1048.65
Mitochondrial_DNA_maintenance_disorder_GA           21131.0      1056.55
Mucopolysaccharideosis,_Gaucher,_Fabry_GA           19555.0       977.75
Peroxisomal_disorders_GA                            20483.0      1024.15
Pyruvate_dehydrogenase_(PDH)_deficiency_GA          19407.0       970.35
Glycogen_storage_disease_GA                         19607.0       980.35
Acute_rhabdomyolysis_GA                             19522.0       976.10
Adult_onset_dystonia,_chorea_or_related_movemen...  19491.0       974.55
Adult_onset_hereditary_spastic_paraplegia_GA        20441.0      1022.05
Adult_onset_leukodystrophy_GA                       19457.0       972.85
Arthrogryposis_GA                                   22666.0      1133.30
Ataxia_and_cerebellar_anomalies_-_narrow_panel_GA   20781.0      1039.05
Autism_GA                                           20350.0      1017.50
Brain_channelopathy_GA                              19549.0       977.45
Cerebellar_hypoplasia_GA                            21126.0      1056.30
Cerebral_vascular_malformations_GA                  22225.0      1111.25
Childhood_onset_dystonia,_chorea_or_related_mov...  19505.0       975.25
Childhood_onset_hereditary_spastic_paraplegia_GA    19566.0       978.30
Congenital_muscular_dystrophy_GA                    19504.0       975.20
Congenital_myaesthenic_syndrome_GA                  21003.0      1050.15
Congenital_myopathy_GA                              20509.0      1025.45
Distal_myopathies_GA                                21153.0      1057.65
Early_onset_dementia_(encompassing_fronto-tempo...  19549.0       977.45
Early_onset_dystonia_GA                             19688.0       984.40
Early_onset_or_syndromic_epilepsy_GA                19001.0       950.05
Familial_dysautonomia_GA                            19588.0       979.40
Hereditary_ataxia_GA                                19500.0       975.00
Hereditary_ataxia_with_onset_in_adulthood_GA        21722.0      1086.10
Hereditary_neuropathy_GA                            20392.0      1019.60
Hereditary_neuropathy_or_pain_disorder_GA           20347.0      1017.35
Hereditary_spastic_paraplegia_GA                    20497.0      1024.85
Holoprosencephaly_-_NOT_chromosomal_GA              22411.0      1120.55
Hydrocephalus_GA                                    22689.0      1134.45
Inherited_white_matter_disorders_GA                 20414.0      1020.70
Intellectual_disability_-_microarray_and_sequen...  19440.0       972.00
Intracerebral_calcification_disorders_GA            20931.0      1046.55
Limb_girdle_muscular_dystrophies,_myofibrillar_...  19526.0       976.30
Malformations_of_cortical_development_GA            20345.0      1017.25
Neuronal_ceroid_lipofuscinosis_GA                   21142.0      1057.10
Neurotransmitter_disorders_GA                       19509.0       975.45
Paediatric_motor_neuronopathies_GA                  21291.0      1064.55
Pain_syndromes_GA                                   19546.0       977.30
Parkinson_Disease_and_Complex_Parkinsonism_GA       19535.0       976.75
Paroxysmal_central_nervous_system_disorders_GA      19515.0       975.75
Rhabdomyolysis_and_metabolic_muscle_disorders_GA    19488.0       974.40
Skeletal_Muscle_Channelopathies_GA                  19739.0       986.95
Structural_basal_ganglia_disorders_GA               19637.0       981.85
White_matter_disorders_and_cerebral_calcificati...  19494.0       974.70
Hereditary_systemic_amyloidosis_GA                  20574.0      1028.70
Rare_genetic_inflammatory_skin_disorders_GA         19463.0       973.15
Anophthalmia_or_microphthalmia_GA                   19704.0       985.20
Bilateral_congenital_or_childhood_onset_catarac...  22703.0      1135.15
Corneal_abnormalities_GA                            21123.0      1056.15
Glaucoma_(developmental)_GA                         19732.0       986.60
Infantile_nystagmus_GA                              19871.0       993.55
Ocular_and_oculo-cutaneous_albinism_GA              22405.0      1120.25
Ocular_coloboma_GA                                  19526.0       976.30
Optic_neuropathy_GA                                 21110.0      1055.50
Retinal_disorders_GA                                22523.0      1126.15
Atypical_haemolytic_uraemic_syndrome_GA             22112.0      1105.60
CAKUT_GA                                            22761.0      1138.05
Cystic_kidney_disease_GA                            20494.0      1024.70
Extreme_early-onset_hypertension_GA                 19559.0       977.95
Nephrocalcinosis_or_nephrolithiasis_GA              19712.0       985.60
Polycystic_liver_disease_GA                         19444.0       972.20
Proteinuric_renal_disease_GA                        19648.0       982.40
Renal_tubulopathies_GA                              19695.0       984.75
Tubulointerstitial_kidney_disease_GA                20624.0      1031.20
Unexplained_kidney_failure_in_young_people_GA       19609.0       980.45
Familial_pulmonary_fibrosis_GA                      19806.0       990.30
Pneumothorax_-_familial_GA                          22158.0      1107.90
Pulmonary_fibrosis_familial_GA                      19673.0       983.65
Ehlers_Danlos_syndrome_with_a_likely_monogenic_...  19718.0       985.90
Periodic_fever_syndromes_GA                         19843.0       992.15
Amelogenesis_imperfecta_GA                          19462.0       973.10
Choanal_atresia_GA                                  21036.0      1051.80
Limb_disorders_GA                                   22571.0      1128.55
Osteogenesis_imperfecta_GA                          19522.0       976.10
Osteopetrosis_GA                                    21029.0      1051.45
Rare_syndromic_craniosynostosis_or_isolated_mul...  19474.0       973.70
Stickler_syndrome_GA                                19705.0       985.25
Thoracic_dystrophies_GA                             20985.0      1049.25
Endocrine_neoplasia_GA                              19702.0       985.10
Familial_breast_cancer_GA                           22255.0      1112.75
Familial_rhabdomyosarcoma_GA                        19586.0       979.30
Familial_Tumours_Syndromes_of_the_central_&_per...  19701.0       985.05
Inherited_ovarian_cancer_(without_breast_cancer...  22256.0      1112.80
Inherited_pancreatic_cancer_GA                      22256.0      1112.80
Inherited_phaeochromocytoma_and_paraganglioma_GA    19579.0       978.95
Inherited_phaeochromocytoma_and_paraganglioma_e...  19655.0       982.75
Inherited_predisposition_to_acute_myeloid_leuka...  19688.0       984.40
Inherited_renal_cancer_GA                           19573.0       978.65
Multiple_endocrine_tumours_GA                       19737.0       986.85
Neurofibromatosis_Type_1_GA                         22228.0      1111.40

In [80]:
top_bottom[top_bottom==True] = "TOP"

/tmp/ipykernel_2438332/2000337921.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'TOP' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  top_bottom[top_bottom==True] = "TOP"

In [81]:
top_bottom[mask_bottom == True] = "BOTTOM"

In [82]:
top_bottom

,Colorectal_cancer_pertinent_cancer_susceptibility_GA,Head_and_neck_cancer_pertinent_cancer_susceptibility_GA,Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA,Renal_cancer_pertinent_cancer_susceptibility_GA,Arrhythmogenic_right_ventricular_cardiomyopathy_GA,ClinGen_Familial_thoracic_aortic_aneurysm_and_aortic_dissection_GA,Dilated_Cardiomyopathy_and_conduction_defects_GA,Familial_cerebral_small_vessel_disease_GA,Familial_non_syndromic_congenital_heart_disease_GA,Hypertrophic_cardiomyopathy_GA,...,Familial_rhabdomyosarcoma_GA,Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA,Inherited_ovarian_cancer_(without_breast_cancer)_GA,Inherited_pancreatic_cancer_GA,Inherited_phaeochromocytoma_and_paraganglioma_GA,Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA,Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA,Inherited_renal_cancer_GA,Multiple_endocrine_tumours_GA,Neurofibromatosis_Type_1_GA
SYMBOL,,,,,,,,,,,,,,,,,,,,,
FAAP20,False,TOP,BOTTOM,False,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,...,False,False,TOP,TOP,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,TOP
FANCM,TOP,False,False,TOP,False,False,False,False,False,BOTTOM,...,TOP,TOP,TOP,TOP,False,False,TOP,False,False,TOP
POT1,TOP,TOP,False,False,False,BOTTOM,False,BOTTOM,BOTTOM,BOTTOM,...,TOP,False,TOP,TOP,BOTTOM,BOTTOM,TOP,TOP,False,TOP
FAAP100,False,TOP,BOTTOM,False,BOTTOM,BOTTOM,BOTTOM,BOTTOM,False,BOTTOM,...,False,False,TOP,TOP,BOTTOM,BOTTOM,TOP,BOTTOM,BOTTOM,TOP
XRCC3,TOP,TOP,False,TOP,False,False,False,False,False,False,...,TOP,TOP,TOP,TOP,False,False,TOP,False,False,TOP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MTSS1L,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,...,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
C2orf71,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,...,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
FAM57B,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,...,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
FAM92A,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,...,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
WISP3,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,...,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM

In [83]:
class_top_bottom

,Cancer Programme+Tumour syndromes,Gastroenterological disorders,Cardiovascular disorders,Haematological and immunological disorders,Ciliopathies,Skeletal disorders,Dermatological disorders,Endocrine disorders,Hearing and ear disorders,Renal and urinary tract disorders,Rheumatological disorders,Growth disorders,Ophthalmological disorders,Respiratory disorders,Neurology and neurodevelopmental disorders,Dysmorphic and congenital abnormality syndromes,Metabolic disorders
SYMBOL,,,,,,,,,,,,,,,,,
FAAP20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FANCM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
POT1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAAP100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
XRCC3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MTSS1L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C2orf71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAM57B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAM92A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WISP3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
## ejemplo:
g = "FANCM"
c = "Cancer Programme+Tumour syndromes"
top_bottom.loc[g,panel_class[panel_class[0]==c][1]]

Colorectal_cancer_pertinent_cancer_susceptibility_GA                          TOP
Head_and_neck_cancer_pertinent_cancer_susceptibility_GA                     False
Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA                    False
Renal_cancer_pertinent_cancer_susceptibility_GA                               TOP
Endocrine_neoplasia_GA                                                        TOP
Familial_breast_cancer_GA                                                     TOP
Familial_rhabdomyosarcoma_GA                                                  TOP
Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA      TOP
Inherited_ovarian_cancer_(without_breast_cancer)_GA                           TOP
Inherited_pancreatic_cancer_GA                                                TOP
Inherited_phaeochromocytoma_and_paraganglioma_GA                            False
Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA              False
Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA                  TOP
Inherited_renal_cancer_GA                                                   False
Multiple_endocrine_tumours_GA                                               False
Neurofibromatosis_Type_1_GA                                                   TOP
Name: FANCM, dtype: object

In [85]:
gene_disease_matrix.loc[g,panel_class[panel_class[0]==c][1]]

Colorectal_cancer_pertinent_cancer_susceptibility_GA                          64.0
Head_and_neck_cancer_pertinent_cancer_susceptibility_GA                        0.0
Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA                    6109.0
Renal_cancer_pertinent_cancer_susceptibility_GA                              579.0
Endocrine_neoplasia_GA                                                       141.0
Familial_breast_cancer_GA                                                    159.0
Familial_rhabdomyosarcoma_GA                                                 143.0
Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA     189.0
Inherited_ovarian_cancer_(without_breast_cancer)_GA                           20.0
Inherited_pancreatic_cancer_GA                                                65.0
Inherited_phaeochromocytoma_and_paraganglioma_GA                            6115.0
Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA              7112.0
Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA                 316.0
Inherited_renal_cancer_GA                                                   6501.0
Multiple_endocrine_tumours_GA                                               3855.0
Neurofibromatosis_Type_1_GA                                                    1.0
Name: FANCM, dtype: float64

In [86]:
for g in top_bottom.index:
    for c in set(panel_class[0]):
        position_class = top_bottom.loc[g,panel_class[panel_class[0]==c][1]]
        top_in_class = np.sum(position_class == "TOP")
        bottom_in_class = np.sum(position_class == "BOTTOM")
        n_panels_class = len(position_class)
        if top_in_class > n_panels_class*0.5:
            class_top_bottom.loc[g, c] = "TOP"
        elif bottom_in_class > n_panels_class*0.5:
            class_top_bottom.loc[g, c] = "BOTTOM"
        else: 
            class_top_bottom.loc[g, c] = "MIDDLE"

In [87]:
class_top_bottom

,Cancer Programme+Tumour syndromes,Gastroenterological disorders,Cardiovascular disorders,Haematological and immunological disorders,Ciliopathies,Skeletal disorders,Dermatological disorders,Endocrine disorders,Hearing and ear disorders,Renal and urinary tract disorders,Rheumatological disorders,Growth disorders,Ophthalmological disorders,Respiratory disorders,Neurology and neurodevelopmental disorders,Dysmorphic and congenital abnormality syndromes,Metabolic disorders
SYMBOL,,,,,,,,,,,,,,,,,
FAAP20,MIDDLE,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,MIDDLE,BOTTOM,BOTTOM,BOTTOM,MIDDLE,BOTTOM
FANCM,TOP,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE
POT1,TOP,MIDDLE,BOTTOM,MIDDLE,MIDDLE,BOTTOM,BOTTOM,MIDDLE,MIDDLE,MIDDLE,BOTTOM,MIDDLE,MIDDLE,TOP,MIDDLE,MIDDLE,MIDDLE
FAAP100,MIDDLE,MIDDLE,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,MIDDLE,MIDDLE,BOTTOM,TOP,BOTTOM,TOP,BOTTOM
XRCC3,TOP,MIDDLE,MIDDLE,MIDDLE,BOTTOM,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,MIDDLE,TOP,MIDDLE,MIDDLE,MIDDLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MTSS1L,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
C2orf71,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
FAM57B,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
FAM92A,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM
WISP3,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM,BOTTOM

In [88]:
gen_n_class_top = np.sum(class_top_bottom == "TOP", axis=1)
gen_n_class_bottom = np.sum(class_top_bottom == "BOTTOM", axis=1)

In [89]:
ranking_n_class = pd.DataFrame(
    {'n_top': gen_n_class_top,
     'n_bottom': gen_n_class_bottom
    })

ranking_n_class

         n_top  n_bottom
SYMBOL
FAAP20       0        14
FANCM        1         0
POT1         2         4
FAAP100      2        11
XRCC3        2         1
...        ...       ...
MTSS1L       0        17
C2orf71      0        17
FAM57B       0        17
FAM92A       0        17
WISP3        0        17

[24757 rows x 2 columns]

In [90]:
ranking_n_class[ranking_n_class["n_top"] > 1]

         n_top  n_bottom
SYMBOL
POT1         2         4
FAAP100      2        11
XRCC3        2         1
TERF2        2         1
CTNNB1      13         0
...        ...       ...
TP53        14         0
TSC1         2         0
TSC2         2         0
WT1          7         0
XPA          2         0

[800 rows x 2 columns]

In [92]:
top_1_class=ranking_n_class.query('n_top == 1 and n_bottom >= 10' )  # hay 17 clases en total. 
top_1_class

          n_top  n_bottom
SYMBOL
EME2          1        12
ZNF350        1        11
SDHAF1        1        10
MND1          1        10
ETAA1         1        10
...         ...       ...
CCDC112       1        14
SPRR2E        1        15
LSMEM2        1        15
TSGA10IP      1        15
C5ORF52       1        16

[251 rows x 2 columns]

Con un threshold de 0.05 y seleccionando genes con una categoría TOP y más de 10 bottom, salen 251 genes.

In [ ]:
#gen="UQCR11"
#list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0]

In [77]:
top_1_class.to_csv("/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/genes_class_specific_laxo.txt")

In [76]:
[x for x in top_1_class.index if x in list(genes_panelApp[0]) ]

['SDHAF1',
 'TERB2',
 'CFAP52',
 'FOXRED1',
 'UQCR10',
 'BLOC1S3',
 'CFAP20',
 'CCDC151',
 'CEP295',
 'RSPH9',
 'R3HCC1',
 'TTC26',
 'CRLF2',
 'TBC1D32',
 'IFT52',
 'DNAAF1',
 'CDSN',
 'WRAP73',
 'HAUS7',
 'ELMOD2',
 'PIBF1',
 'RSPH4A',
 'TTLL9',
 'POC5',
 'FRA10AC1',
 'CASP14',
 'DRC1',
 'AKNA',
 'GJB5',
 'MNS1',
 'CCDC65',
 'CRYBB3',
 'IQCE',
 'OPN1MW',
 'KIZ',
 'CEP78',
 'DZIP1L',
 'TAPT1',
 'IFT74',
 'KRT12',
 'SLC38A8',
 'SOBP',
 'CRYBB1',
 'TUBGCP5',
 'ODF2L',
 'CCDC114',
 'CEP19',
 'BLOC1S5',
 'CFAP46',
 'RENBP',
 'DRAM2',
 'CRYGD',
 'KCTD17',
 'CRYGC',
 'FAM160B1',
 'KRT86',
 'OPN1LW',
 'CCDC28B',
 'TCTEX1D2',
 'TMEM218',
 'CFAP45',
 'PRSS56',
 'CFAP221',
 'KCNJ18']

In [97]:
gene_disease_matrix.loc["FAAP20",panel_class[panel_class[0]=="Cancer Programme+Tumour syndromes"][1]]
#gene_disease_matrix.loc["FAAP20"]

Colorectal_cancer_pertinent_cancer_susceptibility_GA                         5773.0
Head_and_neck_cancer_pertinent_cancer_susceptibility_GA                         4.0
Neuroendocrine_cancer_pertinent_cancer_susceptibility_GA                    13424.0
Renal_cancer_pertinent_cancer_susceptibility_GA                              5967.0
Endocrine_neoplasia_GA                                                       8105.0
Familial_breast_cancer_GA                                                     516.0
Familial_rhabdomyosarcoma_GA                                                 5818.0
Familial_Tumours_Syndromes_of_the_central_&_peripheral_Nervous_system_GA     8198.0
Inherited_ovarian_cancer_(without_breast_cancer)_GA                           564.0
Inherited_pancreatic_cancer_GA                                                493.0
Inherited_phaeochromocytoma_and_paraganglioma_GA                            13937.0
Inherited_phaeochromocytoma_and_paraganglioma_excluding_NF1_GA              14695.0
Inherited_predisposition_to_acute_myeloid_leukaemia_(AML)_GA                 9970.0
Inherited_renal_cancer_GA                                                   11996.0
Multiple_endocrine_tumours_GA                                               12204.0
Neurofibromatosis_Type_1_GA                                                     4.0
Name: FAAP20, dtype: float64

In [45]:
for gen in top_1_class.index: 
    print(gen + ": " + list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0])

EME2: Cancer Programme+Tumour syndromes
ZNF350: Cancer Programme+Tumour syndromes
SDHAF1: Metabolic disorders
MND1: Cancer Programme+Tumour syndromes
ETAA1: Respiratory disorders
RNF212: Cancer Programme+Tumour syndromes
MAJIN: Respiratory disorders
TERB1: Respiratory disorders
TERB2: Respiratory disorders
CFAP52: Ciliopathies
NUPR2: Respiratory disorders
SYCP2: Respiratory disorders
ZNF676: Respiratory disorders
ZBTB48: Respiratory disorders
CCDC9: Respiratory disorders
ADPRH: Respiratory disorders
ZNF208: Respiratory disorders
RPUSD1: Respiratory disorders
FOXRED1: Metabolic disorders
SPAG5: Ciliopathies
UQCR10: Metabolic disorders
FAM207A: Respiratory disorders
PHLDB1: Respiratory disorders
BLOC1S3: Respiratory disorders
CFAP20: Ciliopathies
CCDC151: Ciliopathies
CEP295: Ciliopathies
TBC1D10A: Respiratory disorders
NEK11: Ciliopathies
MPHOSPH10: Respiratory disorders
SLA: Respiratory disorders
CDKL2: Ciliopathies
ZC3H18: Respiratory disorders
ANGEL2: Respiratory disorders
PRB1: Respiratory disorders
FAM118B: Respiratory disorders
MAP9: Ciliopathies
UBXN10: Ciliopathies
RSPH9: Ciliopathies
CCDC18: Ciliopathies
R3HCC1: Respiratory disorders
TRIL: Respiratory disorders
TTC26: Ciliopathies
CRLF2: Respiratory disorders
TBC1D32: Ciliopathies
CEP131: Ciliopathies
M1AP: Respiratory disorders
PEBP4: Respiratory disorders
RFX8: Ciliopathies
CFAP61: Ciliopathies
C9ORF116: Ciliopathies
HRNR: Dermatological disorders
SPRR1B: Dermatological disorders
HAUS5: Ciliopathies
IFT52: Ciliopathies
DNAAF1: Ciliopathies
LRRC36: Respiratory disorders
TTC21A: Ciliopathies
TEKT4: Ciliopathies
CDSN: Dermatological disorders
PRB3: Respiratory disorders
WRAP73: Ciliopathies
EXOC3L1: Respiratory disorders
HAUS7: Ciliopathies
SCGB3A1: Respiratory disorders
ELMOD2: Respiratory disorders
SPAG16: Ciliopathies
PIBF1: Ciliopathies
MTARC1: Respiratory disorders
IFT22: Ciliopathies
RSPH4A: Ciliopathies
PRB4: Respiratory disorders
PUS7L: Respiratory disorders
TTLL3: Ciliopathies
TTLL9: Ciliopathies
KRTCAP3: Dermatological disorders
CDKL1: Ciliopathies
POC5: Ciliopathies
FRA10AC1: Ciliopathies
CEP192: Ciliopathies
RBM7: Respiratory disorders
C10ORF131: Ciliopathies
CASP14: Dermatological disorders
LRRC45: Ciliopathies
MZT2A: Ciliopathies
CC2D2B: Ciliopathies
SPPL2C: Respiratory disorders
CEP128: Ciliopathies
DRC1: Ciliopathies
AKNA: Ciliopathies
PIH1D2: Ciliopathies
ASPHD2: Respiratory disorders
GJB5: Dermatological disorders
IL17RE: Rheumatological disorders
LRRC10: Cardiovascular disorders
ENKUR: Ciliopathies
MNS1: Ciliopathies
CFAP36: Ciliopathies
ZNF17: Ciliopathies
CCDC65: Ciliopathies
DYNLRB2: Ciliopathies
CRYBB3: Ophthalmological disorders
IQCE: Ciliopathies
SPRR3: Dermatological disorders
OPN1MW: Ophthalmological disorders
KIZ: Ciliopathies
LAMP3: Respiratory disorders
S100A7: Dermatological disorders
CEP20: Ciliopathies
CEP72: Ciliopathies
RIBC2: Ciliopathies
RABEP2: Ciliopathies
GLB1L2: Ciliopathies
TCTE3: Ciliopathies
CIART: Respiratory disorders
KRT80: Dermatological disorders
CDKL4: Ciliopathies
CEP78: Ciliopathies
CCDC13: Ciliopathies
GSDMA: Dermatological disorders
MAPK1IP1L: Ciliopathies
DZIP1L: Ciliopathies
MZT1: Ciliopathies
TAPT1: Ciliopathies
HAUS8: Ciliopathies
IFT74: Ciliopathies
SPATA2L: Ciliopathies
BLOC1S4: Respiratory disorders
KRT12: Dermatological disorders
C20ORF194: Ciliopathies
CCDC130: Respiratory disorders
MAP7D2: Ciliopathies
TTC29: Ciliopathies
CEP76: Ciliopathies
CFAP251: Ciliopathies
HAUS4: Ciliopathies
SLC38A8: Ophthalmological disorders
PACRGL: Ciliopathies
FAM161B: Ciliopathies
SOBP: Hearing and ear disorders
SLN: Cardiovascular disorders
CEP162: Ciliopathies
CRYBB1: Ophthalmological disorders
TUBGCP5: Ciliopathies
DNALI1: Ciliopathies
ODF2L: Ciliopathies
C8ORF37: Ciliopathies
CCDC114: Ciliopathies
TTLL6: Ciliopathies
NEK5: Ciliopathies
CEP19: Ciliopathies
RBM11: Respiratory disorders
CCDC77: Ciliopathies
TMEM80: Ciliopathies
CCDC61: Ciliopathies
TRIM4: Ophthalmological disorders
PGA4: Respiratory disorders
ST6GALNAC2: Respiratory disorders
CLTRN: Renal and urinary tract disorders
BLOC1S5: Respiratory disorders
RSPH6A: Ciliopathies
ARL13A: Ciliopathies
TEKT1: Ciliopathies
KRT28: Dermatological disorders
CFAP46: Respiratory disorders
DRC7: Ciliopathies
TMEM79: Respiratory disorders
CDKL3: Ciliopathies
RENBP: Renal and urinary tract disorders
SBSN: Dermatological disorders
KRTDAP: Dermatological disorders
CPM: Respiratory disorders
KRT23: Dermatological disorders
KRT84: Dermatological disorders
KRT24: Dermatological disorders
NXPH4: Ciliopathies
DRAM2: Ophthalmological disorders
SPRR1A: Dermatological disorders
TTLL10: Ciliopathies
CCDC63: Ciliopathies
CRYGD: Ophthalmological disorders
SFTA2: Respiratory disorders
TMEM150A: Respiratory disorders
CCDC14: Ciliopathies
TMEM174: Renal and urinary tract disorders
LYPD4: Respiratory disorders
KCTD17: Ciliopathies
TTLL4: Ciliopathies
CRYGC: Ophthalmological disorders
BIVM: Ciliopathies
RPTN: Dermatological disorders
MTMR10: Ciliopathies
SPRR2A: Dermatological disorders
TMEM268: Respiratory disorders
IQUB: Ciliopathies
FSBP: Respiratory disorders
CCSAP: Ciliopathies
DNAI3: Ciliopathies
CFAP20DC: Ciliopathies
DEUP1: Ciliopathies
FAM160B1: Ciliopathies
TCTEX1D4: Ciliopathies
TTC30B: Ciliopathies
KRT73: Dermatological disorders
KRT86: Dermatological disorders
CCDC66: Ciliopathies
RIBC1: Ciliopathies
OPN1LW: Ophthalmological disorders
CCDC28B: Ciliopathies
SFTA3: Respiratory disorders
TTLL8: Ciliopathies
TCTEX1D2: Ciliopathies
UCN3: Endocrine disorders
CIBAR2: Ciliopathies
FCN2: Respiratory disorders
TMEM17: Ciliopathies
KRT77: Dermatological disorders
TMEM218: Ciliopathies
SPEF1: Ciliopathies
FAM98C: Ciliopathies
CILP2: Rheumatological disorders
CFAP45: Respiratory disorders
CNFN: Dermatological disorders
NPTXR: Respiratory disorders
CCDC138: Ciliopathies
TEX9: Ciliopathies
FCN1: Respiratory disorders
LYPD2: Respiratory disorders
KRT78: Dermatological disorders
RILPL2: Ciliopathies
BPIFB1: Respiratory disorders
KPRP: Dermatological disorders
LCE3D: Dermatological disorders
ZNF385C: Hearing and ear disorders
TSPAN18: Ciliopathies
CCDC113: Ciliopathies
TCTEX1D1: Ciliopathies
TTC36: Ciliopathies
MYADML2: Respiratory disorders
PRSS56: Ophthalmological disorders
CFAP221: Ciliopathies
CFAP299: Ciliopathies
CFAP70: Ciliopathies
SNTN: Respiratory disorders
KCNJ18: Cardiovascular disorders
CCDC146: Ciliopathies
CCDC112: Ciliopathies
SPRR2E: Dermatological disorders
LSMEM2: Respiratory disorders
TSGA10IP: Respiratory disorders
C5ORF52: Ciliopathies

**UQCR10 sale en red en mitocondriales y sale específico de metabolismo**
**SOBP sale en red en monogenic hearing loss y sale específico de hearing disorders**

In [46]:
top_clases = []
for gen in top_1_class.index: 
    top_clases.append(list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0])

from collections import Counter

d = Counter(top_clases)

d

Counter({'Ciliopathies': 130,
         'Respiratory disorders': 65,
         'Dermatological disorders': 28,
         'Ophthalmological disorders': 10,
         'Cancer Programme+Tumour syndromes': 4,
         'Metabolic disorders': 3,
         'Cardiovascular disorders': 3,
         'Renal and urinary tract disorders': 3,
         'Rheumatological disorders': 2,
         'Hearing and ear disorders': 2,
         'Endocrine disorders': 1})

Todos, menos OPN1LW y UQCR11 son específicos de Respiratory disorders o de Ciliopatías.

Relajamos el threshold. Solo los que son top en una categoría (sin restricción de bottom)

In [71]:
top_1_class=ranking_n_class.query('n_top == 1 and n_bottom!=0' )  # hay 17 clases en total. 
#top_1_class=ranking_n_class.query('n_top == 1' ) 
top_1_class

          n_top  n_bottom
SYMBOL
TEN1          1         6
FAAP24        1         8
SLX1A         1         9
POLN          1         5
GTF2H1        1         1
...         ...       ...
TSGA10IP      1        15
C5ORF52       1        16
NTHL1         1         3
PALB2         1         1
WRAP53        1         1

[1174 rows x 2 columns]

In [93]:
for gen in top_1_class.index: 
    print(gen + ": " + list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0])

EME2: Cancer Programme+Tumour syndromes
ZNF350: Cancer Programme+Tumour syndromes
SDHAF1: Metabolic disorders
MND1: Cancer Programme+Tumour syndromes
ETAA1: Respiratory disorders
RNF212: Cancer Programme+Tumour syndromes
MAJIN: Respiratory disorders
TERB1: Respiratory disorders
TERB2: Respiratory disorders
CFAP52: Ciliopathies
NUPR2: Respiratory disorders
SYCP2: Respiratory disorders
ZNF676: Respiratory disorders
ZBTB48: Respiratory disorders
CCDC9: Respiratory disorders
ADPRH: Respiratory disorders
ZNF208: Respiratory disorders
RPUSD1: Respiratory disorders
FOXRED1: Metabolic disorders
SPAG5: Ciliopathies
UQCR10: Metabolic disorders
FAM207A: Respiratory disorders
PHLDB1: Respiratory disorders
BLOC1S3: Respiratory disorders
CFAP20: Ciliopathies
CCDC151: Ciliopathies
CEP295: Ciliopathies
TBC1D10A: Respiratory disorders
NEK11: Ciliopathies
MPHOSPH10: Respiratory disorders
SLA: Respiratory disorders
CDKL2: Ciliopathies
ZC3H18: Respiratory disorders
ANGEL2: Respiratory disorders
PRB1: Respiratory disorders
FAM118B: Respiratory disorders
MAP9: Ciliopathies
UBXN10: Ciliopathies
RSPH9: Ciliopathies
CCDC18: Ciliopathies
R3HCC1: Respiratory disorders
TRIL: Respiratory disorders
TTC26: Ciliopathies
CRLF2: Respiratory disorders
TBC1D32: Ciliopathies
CEP131: Ciliopathies
M1AP: Respiratory disorders
PEBP4: Respiratory disorders
RFX8: Ciliopathies
CFAP61: Ciliopathies
C9ORF116: Ciliopathies
HRNR: Dermatological disorders
SPRR1B: Dermatological disorders
HAUS5: Ciliopathies
IFT52: Ciliopathies
DNAAF1: Ciliopathies
LRRC36: Respiratory disorders
TTC21A: Ciliopathies
TEKT4: Ciliopathies
CDSN: Dermatological disorders
PRB3: Respiratory disorders
WRAP73: Ciliopathies
EXOC3L1: Respiratory disorders
HAUS7: Ciliopathies
SCGB3A1: Respiratory disorders
ELMOD2: Respiratory disorders
SPAG16: Ciliopathies
PIBF1: Ciliopathies
MTARC1: Respiratory disorders
IFT22: Ciliopathies
RSPH4A: Ciliopathies
PRB4: Respiratory disorders
PUS7L: Respiratory disorders
TTLL3: Ciliopathies
TTLL9: Ciliopathies
KRTCAP3: Dermatological disorders
CDKL1: Ciliopathies
POC5: Ciliopathies
FRA10AC1: Ciliopathies
CEP192: Ciliopathies
RBM7: Respiratory disorders
C10ORF131: Ciliopathies
CASP14: Dermatological disorders
LRRC45: Ciliopathies
MZT2A: Ciliopathies
CC2D2B: Ciliopathies
SPPL2C: Respiratory disorders
CEP128: Ciliopathies
DRC1: Ciliopathies
AKNA: Ciliopathies
PIH1D2: Ciliopathies
ASPHD2: Respiratory disorders
GJB5: Dermatological disorders
IL17RE: Rheumatological disorders
LRRC10: Cardiovascular disorders
ENKUR: Ciliopathies
MNS1: Ciliopathies
CFAP36: Ciliopathies
ZNF17: Ciliopathies
CCDC65: Ciliopathies
DYNLRB2: Ciliopathies
CRYBB3: Ophthalmological disorders
IQCE: Ciliopathies
SPRR3: Dermatological disorders
OPN1MW: Ophthalmological disorders
KIZ: Ciliopathies
LAMP3: Respiratory disorders
S100A7: Dermatological disorders
CEP20: Ciliopathies
CEP72: Ciliopathies
RIBC2: Ciliopathies
RABEP2: Ciliopathies
GLB1L2: Ciliopathies
TCTE3: Ciliopathies
CIART: Respiratory disorders
KRT80: Dermatological disorders
CDKL4: Ciliopathies
CEP78: Ciliopathies
CCDC13: Ciliopathies
GSDMA: Dermatological disorders
MAPK1IP1L: Ciliopathies
DZIP1L: Ciliopathies
MZT1: Ciliopathies
TAPT1: Ciliopathies
HAUS8: Ciliopathies
IFT74: Ciliopathies
SPATA2L: Ciliopathies
BLOC1S4: Respiratory disorders
KRT12: Dermatological disorders
C20ORF194: Ciliopathies
CCDC130: Respiratory disorders
MAP7D2: Ciliopathies
TTC29: Ciliopathies
CEP76: Ciliopathies
CFAP251: Ciliopathies
HAUS4: Ciliopathies
SLC38A8: Ophthalmological disorders
PACRGL: Ciliopathies
FAM161B: Ciliopathies
SOBP: Hearing and ear disorders
SLN: Cardiovascular disorders
CEP162: Ciliopathies
CRYBB1: Ophthalmological disorders
TUBGCP5: Ciliopathies
DNALI1: Ciliopathies
ODF2L: Ciliopathies
C8ORF37: Ciliopathies
CCDC114: Ciliopathies
TTLL6: Ciliopathies
NEK5: Ciliopathies
CEP19: Ciliopathies
RBM11: Respiratory disorders
CCDC77: Ciliopathies
TMEM80: Ciliopathies
CCDC61: Ciliopathies
TRIM4: Ophthalmological disorders
PGA4: Respiratory disorders
ST6GALNAC2: Respiratory disorders
CLTRN: Renal and urinary tract disorders
BLOC1S5: Respiratory disorders
RSPH6A: Ciliopathies
ARL13A: Ciliopathies
TEKT1: Ciliopathies
KRT28: Dermatological disorders
CFAP46: Respiratory disorders
DRC7: Ciliopathies
TMEM79: Respiratory disorders
CDKL3: Ciliopathies
RENBP: Renal and urinary tract disorders
SBSN: Dermatological disorders
KRTDAP: Dermatological disorders
CPM: Respiratory disorders
KRT23: Dermatological disorders
KRT84: Dermatological disorders
KRT24: Dermatological disorders
NXPH4: Ciliopathies
DRAM2: Ophthalmological disorders
SPRR1A: Dermatological disorders
TTLL10: Ciliopathies
CCDC63: Ciliopathies
CRYGD: Ophthalmological disorders
SFTA2: Respiratory disorders
TMEM150A: Respiratory disorders
CCDC14: Ciliopathies
TMEM174: Renal and urinary tract disorders
LYPD4: Respiratory disorders
KCTD17: Ciliopathies
TTLL4: Ciliopathies
CRYGC: Ophthalmological disorders
BIVM: Ciliopathies
RPTN: Dermatological disorders
MTMR10: Ciliopathies
SPRR2A: Dermatological disorders
TMEM268: Respiratory disorders
IQUB: Ciliopathies
FSBP: Respiratory disorders
CCSAP: Ciliopathies
DNAI3: Ciliopathies
CFAP20DC: Ciliopathies
DEUP1: Ciliopathies
FAM160B1: Ciliopathies
TCTEX1D4: Ciliopathies
TTC30B: Ciliopathies
KRT73: Dermatological disorders
KRT86: Dermatological disorders
CCDC66: Ciliopathies
RIBC1: Ciliopathies
OPN1LW: Ophthalmological disorders
CCDC28B: Ciliopathies
SFTA3: Respiratory disorders
TTLL8: Ciliopathies
TCTEX1D2: Ciliopathies
UCN3: Endocrine disorders
CIBAR2: Ciliopathies
FCN2: Respiratory disorders
TMEM17: Ciliopathies
KRT77: Dermatological disorders
TMEM218: Ciliopathies
SPEF1: Ciliopathies
FAM98C: Ciliopathies
CILP2: Rheumatological disorders
CFAP45: Respiratory disorders
CNFN: Dermatological disorders
NPTXR: Respiratory disorders
CCDC138: Ciliopathies
TEX9: Ciliopathies
FCN1: Respiratory disorders
LYPD2: Respiratory disorders
KRT78: Dermatological disorders
RILPL2: Ciliopathies
BPIFB1: Respiratory disorders
KPRP: Dermatological disorders
LCE3D: Dermatological disorders
ZNF385C: Hearing and ear disorders
TSPAN18: Ciliopathies
CCDC113: Ciliopathies
TCTEX1D1: Ciliopathies
TTC36: Ciliopathies
MYADML2: Respiratory disorders
PRSS56: Ophthalmological disorders
CFAP221: Ciliopathies
CFAP299: Ciliopathies
CFAP70: Ciliopathies
SNTN: Respiratory disorders
KCNJ18: Cardiovascular disorders
CCDC146: Ciliopathies
CCDC112: Ciliopathies
SPRR2E: Dermatological disorders
LSMEM2: Respiratory disorders
TSGA10IP: Respiratory disorders
C5ORF52: Ciliopathies

In [94]:
class_specific = {}
for gen in top_1_class.index: 
    class_specific[gen] = list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0]
    #print(gen + ": " + list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0])

In [95]:
class_specific

{'EME2': 'Cancer Programme+Tumour syndromes',
 'ZNF350': 'Cancer Programme+Tumour syndromes',
 'SDHAF1': 'Metabolic disorders',
 'MND1': 'Cancer Programme+Tumour syndromes',
 'ETAA1': 'Respiratory disorders',
 'RNF212': 'Cancer Programme+Tumour syndromes',
 'MAJIN': 'Respiratory disorders',
 'TERB1': 'Respiratory disorders',
 'TERB2': 'Respiratory disorders',
 'CFAP52': 'Ciliopathies',
 'NUPR2': 'Respiratory disorders',
 'SYCP2': 'Respiratory disorders',
 'ZNF676': 'Respiratory disorders',
 'ZBTB48': 'Respiratory disorders',
 'CCDC9': 'Respiratory disorders',
 'ADPRH': 'Respiratory disorders',
 'ZNF208': 'Respiratory disorders',
 'RPUSD1': 'Respiratory disorders',
 'FOXRED1': 'Metabolic disorders',
 'SPAG5': 'Ciliopathies',
 'UQCR10': 'Metabolic disorders',
 'FAM207A': 'Respiratory disorders',
 'PHLDB1': 'Respiratory disorders',
 'BLOC1S3': 'Respiratory disorders',
 'CFAP20': 'Ciliopathies',
 'CCDC151': 'Ciliopathies',
 'CEP295': 'Ciliopathies',
 'TBC1D10A': 'Respiratory disorders',
 'NEK11': 'Ciliopathies',
 'MPHOSPH10': 'Respiratory disorders',
 'SLA': 'Respiratory disorders',
 'CDKL2': 'Ciliopathies',
 'ZC3H18': 'Respiratory disorders',
 'ANGEL2': 'Respiratory disorders',
 'PRB1': 'Respiratory disorders',
 'FAM118B': 'Respiratory disorders',
 'MAP9': 'Ciliopathies',
 'UBXN10': 'Ciliopathies',
 'RSPH9': 'Ciliopathies',
 'CCDC18': 'Ciliopathies',
 'R3HCC1': 'Respiratory disorders',
 'TRIL': 'Respiratory disorders',
 'TTC26': 'Ciliopathies',
 'CRLF2': 'Respiratory disorders',
 'TBC1D32': 'Ciliopathies',
 'CEP131': 'Ciliopathies',
 'M1AP': 'Respiratory disorders',
 'PEBP4': 'Respiratory disorders',
 'RFX8': 'Ciliopathies',
 'CFAP61': 'Ciliopathies',
 'C9ORF116': 'Ciliopathies',
 'HRNR': 'Dermatological disorders',
 'SPRR1B': 'Dermatological disorders',
 'HAUS5': 'Ciliopathies',
 'IFT52': 'Ciliopathies',
 'DNAAF1': 'Ciliopathies',
 'LRRC36': 'Respiratory disorders',
 'TTC21A': 'Ciliopathies',
 'TEKT4': 'Ciliopathies',
 'CDSN': 'Dermatological disorders',
 'PRB3': 'Respiratory disorders',
 'WRAP73': 'Ciliopathies',
 'EXOC3L1': 'Respiratory disorders',
 'HAUS7': 'Ciliopathies',
 'SCGB3A1': 'Respiratory disorders',
 'ELMOD2': 'Respiratory disorders',
 'SPAG16': 'Ciliopathies',
 'PIBF1': 'Ciliopathies',
 'MTARC1': 'Respiratory disorders',
 'IFT22': 'Ciliopathies',
 'RSPH4A': 'Ciliopathies',
 'PRB4': 'Respiratory disorders',
 'PUS7L': 'Respiratory disorders',
 'TTLL3': 'Ciliopathies',
 'TTLL9': 'Ciliopathies',
 'KRTCAP3': 'Dermatological disorders',
 'CDKL1': 'Ciliopathies',
 'POC5': 'Ciliopathies',
 'FRA10AC1': 'Ciliopathies',
 'CEP192': 'Ciliopathies',
 'RBM7': 'Respiratory disorders',
 'C10ORF131': 'Ciliopathies',
 'CASP14': 'Dermatological disorders',
 'LRRC45': 'Ciliopathies',
 'MZT2A': 'Ciliopathies',
 'CC2D2B': 'Ciliopathies',
 'SPPL2C': 'Respiratory disorders',
 'CEP128': 'Ciliopathies',
 'DRC1': 'Ciliopathies',
 'AKNA': 'Ciliopathies',
 'PIH1D2': 'Ciliopathies',
 'ASPHD2': 'Respiratory disorders',
 'GJB5': 'Dermatological disorders',
 'IL17RE': 'Rheumatological disorders',
 'LRRC10': 'Cardiovascular disorders',
 'ENKUR': 'Ciliopathies',
 'MNS1': 'Ciliopathies',
 'CFAP36': 'Ciliopathies',
 'ZNF17': 'Ciliopathies',
 'CCDC65': 'Ciliopathies',
 'DYNLRB2': 'Ciliopathies',
 'CRYBB3': 'Ophthalmological disorders',
 'IQCE': 'Ciliopathies',
 'SPRR3': 'Dermatological disorders',
 'OPN1MW': 'Ophthalmological disorders',
 'KIZ': 'Ciliopathies',
 'LAMP3': 'Respiratory disorders',
 'S100A7': 'Dermatological disorders',
 'CEP20': 'Ciliopathies',
 'CEP72': 'Ciliopathies',
 'RIBC2': 'Ciliopathies',
 'RABEP2': 'Ciliopathies',
 'GLB1L2': 'Ciliopathies',
 'TCTE3': 'Ciliopathies',
 'CIART': 'Respiratory disorders',
 'KRT80': 'Dermatological disorders',
 'CDKL4': 'Ciliopathies',
 'CEP78': 'Ciliopathies',
 'CCDC13': 'Ciliopathies',
 'GSDMA': 'Dermatological disorders',
 'MAPK1IP1L': 'Ciliopathies',
 'DZIP1L': 'Ciliopathies',
 'MZT1': 'Ciliopathies',
 'TAPT1': 'Ciliopathies',
 'HAUS8': 'Ciliopathies',
 'IFT74': 'Ciliopathies',
 'SPATA2L': 'Ciliopathies',
 'BLOC1S4': 'Respiratory disorders',
 'KRT12': 'Dermatological disorders',
 'C20ORF194': 'Ciliopathies',
 'CCDC130': 'Respiratory disorders',
 'MAP7D2': 'Ciliopathies',
 'TTC29': 'Ciliopathies',
 'CEP76': 'Ciliopathies',
 'CFAP251': 'Ciliopathies',
 'HAUS4': 'Ciliopathies',
 'SLC38A8': 'Ophthalmological disorders',
 'PACRGL': 'Ciliopathies',
 'FAM161B': 'Ciliopathies',
 'SOBP': 'Hearing and ear disorders',
 'SLN': 'Cardiovascular disorders',
 'CEP162': 'Ciliopathies',
 'CRYBB1': 'Ophthalmological disorders',
 'TUBGCP5': 'Ciliopathies',
 'DNALI1': 'Ciliopathies',
 'ODF2L': 'Ciliopathies',
 'C8ORF37': 'Ciliopathies',
 'CCDC114': 'Ciliopathies',
 'TTLL6': 'Ciliopathies',
 'NEK5': 'Ciliopathies',
 'CEP19': 'Ciliopathies',
 'RBM11': 'Respiratory disorders',
 'CCDC77': 'Ciliopathies',
 'TMEM80': 'Ciliopathies',
 'CCDC61': 'Ciliopathies',
 'TRIM4': 'Ophthalmological disorders',
 'PGA4': 'Respiratory disorders',
 'ST6GALNAC2': 'Respiratory disorders',
 'CLTRN': 'Renal and urinary tract disorders',
 'BLOC1S5': 'Respiratory disorders',
 'RSPH6A': 'Ciliopathies',
 'ARL13A': 'Ciliopathies',
 'TEKT1': 'Ciliopathies',
 'KRT28': 'Dermatological disorders',
 'CFAP46': 'Respiratory disorders',
 'DRC7': 'Ciliopathies',
 'TMEM79': 'Respiratory disorders',
 'CDKL3': 'Ciliopathies',
 'RENBP': 'Renal and urinary tract disorders',
 'SBSN': 'Dermatological disorders',
 'KRTDAP': 'Dermatological disorders',
 'CPM': 'Respiratory disorders',
 'KRT23': 'Dermatological disorders',
 'KRT84': 'Dermatological disorders',
 'KRT24': 'Dermatological disorders',
 'NXPH4': 'Ciliopathies',
 'DRAM2': 'Ophthalmological disorders',
 'SPRR1A': 'Dermatological disorders',
 'TTLL10': 'Ciliopathies',
 'CCDC63': 'Ciliopathies',
 'CRYGD': 'Ophthalmological disorders',
 'SFTA2': 'Respiratory disorders',
 'TMEM150A': 'Respiratory disorders',
 'CCDC14': 'Ciliopathies',
 'TMEM174': 'Renal and urinary tract disorders',
 'LYPD4': 'Respiratory disorders',
 'KCTD17': 'Ciliopathies',
 'TTLL4': 'Ciliopathies',
 'CRYGC': 'Ophthalmological disorders',
 'BIVM': 'Ciliopathies',
 'RPTN': 'Dermatological disorders',
 'MTMR10': 'Ciliopathies',
 'SPRR2A': 'Dermatological disorders',
 'TMEM268': 'Respiratory disorders',
 'IQUB': 'Ciliopathies',
 'FSBP': 'Respiratory disorders',
 'CCSAP': 'Ciliopathies',
 'DNAI3': 'Ciliopathies',
 'CFAP20DC': 'Ciliopathies',
 'DEUP1': 'Ciliopathies',
 'FAM160B1': 'Ciliopathies',
 'TCTEX1D4': 'Ciliopathies',
 'TTC30B': 'Ciliopathies',
 'KRT73': 'Dermatological disorders',
 'KRT86': 'Dermatological disorders',
 'CCDC66': 'Ciliopathies',
 'RIBC1': 'Ciliopathies',
 'OPN1LW': 'Ophthalmological disorders',
 'CCDC28B': 'Ciliopathies',
 'SFTA3': 'Respiratory disorders',
 'TTLL8': 'Ciliopathies',
 'TCTEX1D2': 'Ciliopathies',
 'UCN3': 'Endocrine disorders',
 'CIBAR2': 'Ciliopathies',
 'FCN2': 'Respiratory disorders',
 'TMEM17': 'Ciliopathies',
 'KRT77': 'Dermatological disorders',
 'TMEM218': 'Ciliopathies',
 'SPEF1': 'Ciliopathies',
 'FAM98C': 'Ciliopathies',
 'CILP2': 'Rheumatological disorders',
 'CFAP45': 'Respiratory disorders',
 'CNFN': 'Dermatological disorders',
 'NPTXR': 'Respiratory disorders',
 'CCDC138': 'Ciliopathies',
 'TEX9': 'Ciliopathies',
 'FCN1': 'Respiratory disorders',
 'LYPD2': 'Respiratory disorders',
 'KRT78': 'Dermatological disorders',
 'RILPL2': 'Ciliopathies',
 'BPIFB1': 'Respiratory disorders',
 'KPRP': 'Dermatological disorders',
 'LCE3D': 'Dermatological disorders',
 'ZNF385C': 'Hearing and ear disorders',
 'TSPAN18': 'Ciliopathies',
 'CCDC113': 'Ciliopathies',
 'TCTEX1D1': 'Ciliopathies',
 'TTC36': 'Ciliopathies',
 'MYADML2': 'Respiratory disorders',
 'PRSS56': 'Ophthalmological disorders',
 'CFAP221': 'Ciliopathies',
 'CFAP299': 'Ciliopathies',
 'CFAP70': 'Ciliopathies',
 'SNTN': 'Respiratory disorders',
 'KCNJ18': 'Cardiovascular disorders',
 'CCDC146': 'Ciliopathies',
 'CCDC112': 'Ciliopathies',
 'SPRR2E': 'Dermatological disorders',
 'LSMEM2': 'Respiratory disorders',
 'TSGA10IP': 'Respiratory disorders',
 'C5ORF52': 'Ciliopathies'}

In [96]:
df_class_specific = pd.DataFrame.from_dict(class_specific, orient = "index", columns=["Class"])

In [97]:
df_class_specific.to_csv("/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/genes_class_specific_class.csv", header=False)

In [77]:
top_clases = []
for gen in top_1_class.index: 
    top_clases.append(list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0])

In [78]:
from collections import Counter

d = Counter(top_clases)

d

Counter({'Ciliopathies': 116,
         'Respiratory disorders': 65,
         'Hearing and ear disorders': 10,
         'Cancer Programme+Tumour syndromes': 7,
         'Dermatological disorders': 6,
         'Cardiovascular disorders': 4,
         'Ophthalmological disorders': 3,
         'Growth disorders': 1,
         'Endocrine disorders': 1,
         'Haematological and immunological disorders': 1,
         'Metabolic disorders': 1})

In [39]:
import pandas as pd
genes_top1_class = pd.read_csv('/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/genes_class_specific.txt',sep = ',') 
genes_top1_class
#genes_panelApp = pd.read_csv('/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/PANELAPP_ALL_GENES_sep.txt',sep = '\t', header=None) 
#genes_panelApp

      SYMBOL  n_top  n_bottom
0       POT1      1         4
1      TERF2      1         1
2       MSH3      1         0
3      RAD51      1         0
4       TEN1      1         6
..       ...    ...       ...
369     SDHA      1         0
370  SMARCA4      1         0
371     TSC2      1         0
372   WRAP53      1         1
373      XPA      1         0

[374 rows x 3 columns]

In [40]:
[x for x in genes_top1_class["SYMBOL"] if x in list(genes_panelApp[0]) ]

['POT1',
 'TERF2',
 'MSH3',
 'RAD51',
 'TERF2IP',
 'FAN1',
 'STN1',
 'RPA1',
 'MDM2',
 'ATR',
 'PIK3CA',
 'NBN',
 'XRCC2',
 'BARD1',
 'MRE11',
 'RECQL4',
 'DCLRE1B',
 'XRCC1',
 'RAD50',
 'ATRX',
 'CCND1',
 'KLLN',
 'EGFR',
 'PDGFRA',
 'EP300',
 'FGFR2',
 'USB1',
 'MSH5',
 'MSH4',
 'SMC1A',
 'KMT2D',
 'STAT3',
 'IDH1',
 'GLI3',
 'ARID1B',
 'ERBB3',
 'FOS',
 'SMO',
 'CCNA2',
 'IGF2',
 'GNA11',
 'PAX6',
 'BMP4',
 'PLK4',
 'GLI2',
 'GJA1',
 'STAT5A',
 'IGF1',
 'INS',
 'PAX2',
 'FGF8',
 'PCNT',
 'PAX8',
 'EGR2',
 'SHQ1',
 'MDH2',
 'HDAC3',
 'TPP1',
 'CSF2',
 'NEK2',
 'BBS4',
 'BMP2',
 'FOXC1',
 'RPGRIP1L',
 'FN1',
 'LYST',
 'CDK20',
 'BMP7',
 'CEP290',
 'CENPJ',
 'PAX1',
 'EPOR',
 'B9D1',
 'RAB23',
 'IFT172',
 'SMG6',
 'COL7A1',
 'DYNC2H1',
 'CC2D2A',
 'UPF1',
 'EIF2AK4',
 'ALX4',
 'FGF20',
 'POC1A',
 'KRT5',
 'OGDH',
 'IFT140',
 'STIL',
 'COL2A1',
 'OCA2',
 'POMC',
 'SOX3',
 'ISL1',
 'TERB2',
 'NEUROD1',
 'IFT88',
 'EXOSC3',
 'FOXJ1',
 'MSX1',
 'IFT80',
 'IL3',
 'FOXD3',
 'IFT122',
 'HPS6',
 'KRT9',
 'WDR19',
 'SIX2',
 'DLX5',
 'FUZ',
 'SERPINA1',
 'EXOSC8',
 'HOXB1',
 'CEP152',
 'IFT27',
 'TULP3',
 'AP3D1',
 'HPS5',
 'APOA1',
 'NPHP3',
 'HPS3',
 'IL17RD',
 'SLC45A2',
 'DYNC2LI1',
 'PRRX1',
 'EXOSC2',
 'MYL2',
 'LAMA4',
 'DMBT1',
 'ARL3',
 'GJA5',
 'NEK9',
 'IL3RA',
 'EXOSC1',
 'DSG1',
 'KIF3B',
 'KIF17',
 'BLOC1S3',
 'CFAP20',
 'RPGRIP1',
 'DCTN1',
 'CEP295',
 'NEUROG1',
 'CRYBA4',
 'RFX3',
 'CEP135',
 'POU3F3',
 'RPGR',
 'GBX2',
 'CBY1',
 'RYR2',
 'NEK8',
 'SIX3',
 'GALC',
 'PDE6D',
 'RFX4',
 'MAK',
 'DYNC1H1',
 'INTU',
 'GAS8',
 'KRT16',
 'TTC21B',
 'GPR161',
 'BBIP1',
 'ACAD9',
 'TTBK2',
 'PKD1L1',
 'DTNBP1',
 'RAX',
 'BLOC1S6',
 'SASS6',
 'CACNB2',
 'CEP63',
 'AQP5',
 'KCNQ1',
 'FBF1',
 'KRT6A',
 'NPPA',
 'TTC26',
 'TBC1D32',
 'SPATA7',
 'RP2',
 'GSX2',
 'KRT6B',
 'DYNC1I2',
 'RAB32',
 'CROCC',
 'NIN',
 'MYL3',
 'NPHP4',
 'ELMOD2',
 'CLUAP1',
 'CEP83',
 'CASQ2',
 'FAM161A',
 'MYOZ2',
 'DSC1',
 'KCNA5',
 'CEP250',
 'IFT81',
 'CRYAA',
 'CEP78',
 'IFT74',
 'SFTPD',
 'CEP89',
 'NUDCD3',
 'CEP19',
 'LCA5',
 'CCDC28B',
 'TCTEX1D2',
 'BRCA2',
 'CDH1',
 'CDKN2A',
 'CHEK2',
 'ERCC1',
 'ERCC4',
 'ERCC5',
 'HRAS',
 'KRAS',
 'PTCH1',
 'RAD51D',
 'RB1',
 'SDHA',
 'SMARCA4',
 'TSC2',
 'WRAP53',
 'XPA']

ELMOD2 está en los red de Familial pulmonary fibrosis
IFT74 red en Renal ciliopathies
CCDC28B red en varias ciliopathies

Vamos a probar añadiendo la condición de que el 50% de los paneles tienen que estar en el bottom (183 paneles * 0.5 = 91 paneles):

In [47]:
top_1_class=ranking_n_class.query('n_top == 1' )  # hay 17 clases en total. 
top_1_class

          n_top  n_bottom
SYMBOL
POT1          1         4
TERF2         1         1
TEN1          1         6
TERF2IP       1         3
FAN1          1         2
...         ...       ...
TCTEX1D1      1        13
SNTN          1        16
C5ORF52       1        16
ERCC4         1         1
WRAP53        1         1

[215 rows x 2 columns]

In [42]:
bottom_05 = ranking_n[ranking_n["n_bottom"] > 91] 
bottom_05

         n_top  n_bottom
SYMBOL
FAAP20      11       139
FAAP100     14       117
TEN1        12        96
CENPS       11        95
KLLN        15        96
...        ...       ...
MTSS1L       0       182
C2orf71      0       182
FAM57B       0       182
FAM92A       0       182
WISP3        0       183

[14318 rows x 2 columns]

In [43]:
esp_clase_05 = [x for x in list(top_1_class.index) if x in list(bottom_05.index)]

In [46]:
top_1_class_05= top_1_class.loc[esp_clase_05]
top_1_class_05

          n_top  n_bottom
SYMBOL
TEN1          1         6
KLLN          1         9
USB1          1         5
SHQ1          1         9
HMBOX1        1         7
...         ...       ...
LYPD2         1        13
BPIFB1        1        11
TCTEX1D1      1        13
SNTN          1        16
C5ORF52       1        16

[93 rows x 2 columns]

In [80]:
for gen in top_1_class_05.index: 
    print(gen + ": " + list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0])

TEN1: Respiratory disorders
KLLN: Cancer Programme+Tumour syndromes
USB1: Respiratory disorders
SHQ1: Respiratory disorders
HMBOX1: Respiratory disorders
MAJIN: Respiratory disorders
TERB2: Respiratory disorders
SPOUT1: Respiratory disorders
NUPR2: Respiratory disorders
KRT9: Dermatological disorders
ADPRH: Respiratory disorders
EXOSC1: Respiratory disorders
BLOC1S3: Respiratory disorders
CFAP20: Ciliopathies
CEP295: Ciliopathies
EXOSC7: Respiratory disorders
CRYBA4: Ophthalmological disorders
GAS8: Ciliopathies
KRT16: Dermatological disorders
MOK: Ciliopathies
BBIP1: Ciliopathies
PKD1L1: Ciliopathies
CLDN18: Respiratory disorders
UBXN10: Ciliopathies
CCDC18: Ciliopathies
FBF1: Ciliopathies
TTC26: Ciliopathies
TBC1D32: Ciliopathies
CEP131: Ciliopathies
SPATA7: Ciliopathies
RP2: Ciliopathies
KRT6B: Dermatological disorders
PIFO: Ciliopathies
TTC21A: Ciliopathies
ODF2: Ciliopathies
KATNIP: Ciliopathies
IFT46: Ciliopathies
IL5RA: Respiratory disorders
SCGB3A1: Respiratory disorders
ELMOD2: Respiratory disorders
CLUAP1: Ciliopathies
IFT20: Ciliopathies
IFT22: Ciliopathies
CEP83: Ciliopathies
ADGRF5: Respiratory disorders
TBCC: Ciliopathies
CDKL1: Ciliopathies
CEP192: Ciliopathies
RBM7: Respiratory disorders
C10ORF131: Ciliopathies
FAM161A: Ciliopathies
BPIFA1: Respiratory disorders
CC2D2B: Ciliopathies
DSC1: Dermatological disorders
SCGB3A2: Respiratory disorders
CFAP36: Ciliopathies
DYNLRB2: Ciliopathies
LRRCC1: Ciliopathies
IFT81: Ciliopathies
CEP20: Ciliopathies
TCTE3: Ciliopathies
CDKL4: Ciliopathies
CEP78: Ciliopathies
IFT74: Ciliopathies
CEP76: Ciliopathies
CEP89: Ciliopathies
CEP162: Ciliopathies
NUDCD3: Ciliopathies
CEP19: Ciliopathies
RBM11: Respiratory disorders
TMEM80: Ciliopathies
PGA4: Respiratory disorders
ARL13A: Ciliopathies
PGA3: Respiratory disorders
CCDC63: Ciliopathies
SFTA2: Respiratory disorders
CCDC14: Ciliopathies
BIVM: Ciliopathies
TTC30A: Ciliopathies
TMEM268: Respiratory disorders
TCTEX1D4: Ciliopathies
TTC30B: Ciliopathies
CCDC66: Ciliopathies
CCDC28B: Ciliopathies
SFTA3: Respiratory disorders
TCTEX1D2: Ciliopathies
TMEM17: Ciliopathies
TEX9: Ciliopathies
LYPD2: Respiratory disorders
BPIFB1: Respiratory disorders
TCTEX1D1: Ciliopathies
SNTN: Respiratory disorders
C5ORF52: Ciliopathies

In [45]:
top_clases_05 = []
for gen in top_1_class_05.index: 
    top_clases_05.append(list(class_top_bottom.loc[gen][class_top_bottom.loc[gen] == "TOP"].index)[0])

In [143]:
from collections import Counter

d = Counter(top_clases_05)

d

Counter({'Ciliopathies': 58,
         'Respiratory disorders': 29,
         'Dermatological disorders': 4,
         'Cancer Programme+Tumour syndromes': 1,
         'Ophthalmological disorders': 1})

In [146]:
top_1_class_05.to_csv("/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/genes_class_specific_05.txt")

In [147]:
ranking_n_class.query('n_top > 1' )

        n_top  n_bottom
SYMBOL
CTNNB1      4         0
BLM         2         0
WRN         2         0
AKT1        4         0
MYC         2         0
FGFR1       2         0
JAK2        3         0
ESR1        2         0
SHH         3         0
SOX9        2         0
WNT5A       2         0
IRS1        2         0
POU5F1      2         0
ATM         2         0
BRCA1       2         0
CDK4        2         0
KIT         3         0
TP53        3         0

# Vemos si hay específicos de clase dentro de los específicos de enfermedad

In [91]:
list(top_1.index) in list(top_1_class.index)

False

In [92]:
[(x in list(top_1_class.index)) for x in list(top_1.index)]

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [110]:
def intersection(lst1, lst2):
    return list(set(lst1) & set(lst2))

print(intersection(list(top_1_class.index), list(top_1.index)))

[]

No coincide ningún gen.

----------

In [94]:
top_2_class=ranking_n_class.query('n_top == 0' )  # hay 17 clases en total. 
top_2_class # No hay casi paneles con más de una clase top???? raro?

         n_top  n_bottom
SYMBOL
FAAP20       0        14
UBE2T        0         0
CENPS        0        10
GTF2H4       0         3
NOP10        0         3
...        ...       ...
MTSS1L       0        17
C2orf71      0        17
FAM57B       0        17
FAM92A       0        17
WISP3        0        17

[21869 rows x 2 columns]

In [108]:
ranking_n["n_panels"] = 181
ranking_n

         n_top  n_bottom  n_panels
SYMBOL
FAAP20      16       135       181
FANCM       25         6       181
POT1        19        56       181
FAAP100     18       108       181
XRCC3       20        17       181
...        ...       ...       ...
MTSS1L       0       180       181
C2orf71      0       180       181
FAM57B       0       180       181
FAM92A       0       180       181
WISP3        0       180       181

[24757 rows x 3 columns]

In [110]:
specificity_score = (ranking_n["n_top"] / 181 ) * (ranking_n["n_bottom"] / 181 )

In [111]:
specificity_score /= (ranking_n["n_top"] + 1)

In [112]:
specificity_score

SYMBOL
FAAP20     0.003878
FANCM      0.000176
POT1       0.001624
FAAP100    0.003123
XRCC3      0.000494
             ...
MTSS1L     0.000000
C2orf71    0.000000
FAM57B     0.000000
FAM92A     0.000000
WISP3      0.000000
Length: 24757, dtype: float64

In [113]:
specificity_score["SYMBOL"] = specificity_score.index

In [114]:
specificity_score

SYMBOL
FAAP20                                              0.003878
FANCM                                               0.000176
POT1                                                0.001624
FAAP100                                             0.003123
XRCC3                                               0.000494
                                 ...
C2orf71                                                  0.0
FAM57B                                                   0.0
FAM92A                                                   0.0
WISP3                                                    0.0
SYMBOL     Index(['FAAP20', 'FANCM', 'POT1', 'FAAP100', '...
Length: 24758, dtype: object

In [116]:
#specificity_score.to_csv("/home/yolanda/tblab/yolanda/GLOWgenes/panelAPP/analysis/genes_specific/score_prueba.txt")